/*
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.scrapebadger.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StreamMonitorCreate
 */
public class StreamMonitorCreateTest {
    private final StreamMonitorCreate model = new StreamMonitorCreate();

    /**
     * Model tests for StreamMonitorCreate
     */
    @Test
    public void testStreamMonitorCreate() {
        // TODO: test StreamMonitorCreate
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'usernames'
     */
    @Test
    public void usernamesTest() {
        // TODO: test usernames
    }

    /**
     * Test the property 'webhookUrl'
     */
    @Test
    public void webhookUrlTest() {
        // TODO: test webhookUrl
    }

    /**
     * Test the property 'webhookSecret'
     */
    @Test
    public void webhookSecretTest() {
        // TODO: test webhookSecret
    }

    /**
     * Test the property 'filterTypes'
     */
    @Test
    public void filterTypesTest() {
        // TODO: test filterTypes
    }

}
