/*
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.scrapebadger.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VintedPhoto
 */
public class VintedPhotoTest {
    private final VintedPhoto model = new VintedPhoto();

    /**
     * Model tests for VintedPhoto
     */
    @Test
    public void testVintedPhoto() {
        // TODO: test VintedPhoto
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'dominantColor'
     */
    @Test
    public void dominantColorTest() {
        // TODO: test dominantColor
    }

    /**
     * Test the property 'isMain'
     */
    @Test
    public void isMainTest() {
        // TODO: test isMain
    }

    /**
     * Test the property 'width'
     */
    @Test
    public void widthTest() {
        // TODO: test width
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'fullSizeUrl'
     */
    @Test
    public void fullSizeUrlTest() {
        // TODO: test fullSizeUrl
    }

}
