/*
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.scrapebadger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.scrapebadger.client.JSON;

/**
 * Billing activity log entry.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class BillingLogResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_MONITOR_ID = "monitor_id";
  @SerializedName(SERIALIZED_NAME_MONITOR_ID)
  @javax.annotation.Nonnull
  private String monitorId;

  public static final String SERIALIZED_NAME_MONITOR_NAME = "monitor_name";
  @SerializedName(SERIALIZED_NAME_MONITOR_NAME)
  @javax.annotation.Nonnull
  private String monitorName;

  public static final String SERIALIZED_NAME_BILLED_AT = "billed_at";
  @SerializedName(SERIALIZED_NAME_BILLED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime billedAt;

  public static final String SERIALIZED_NAME_NUM_ACCOUNTS = "num_accounts";
  @SerializedName(SERIALIZED_NAME_NUM_ACCOUNTS)
  @javax.annotation.Nonnull
  private Integer numAccounts;

  public static final String SERIALIZED_NAME_CREDITS_DEDUCTED = "credits_deducted";
  @SerializedName(SERIALIZED_NAME_CREDITS_DEDUCTED)
  @javax.annotation.Nonnull
  private BigDecimal creditsDeducted;

  public static final String SERIALIZED_NAME_TIER_LABEL = "tier_label";
  @SerializedName(SERIALIZED_NAME_TIER_LABEL)
  @javax.annotation.Nonnull
  private String tierLabel;

  public static final String SERIALIZED_NAME_RATE_APPLIED = "rate_applied";
  @SerializedName(SERIALIZED_NAME_RATE_APPLIED)
  @javax.annotation.Nonnull
  private BigDecimal rateApplied;

  public BillingLogResponse() {
  }

  public BillingLogResponse id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public BillingLogResponse monitorId(@javax.annotation.Nonnull String monitorId) {
    this.monitorId = monitorId;
    return this;
  }

  /**
   * Get monitorId
   * @return monitorId
   */
  @javax.annotation.Nonnull
  public String getMonitorId() {
    return monitorId;
  }

  public void setMonitorId(@javax.annotation.Nonnull String monitorId) {
    this.monitorId = monitorId;
  }


  public BillingLogResponse monitorName(@javax.annotation.Nonnull String monitorName) {
    this.monitorName = monitorName;
    return this;
  }

  /**
   * Get monitorName
   * @return monitorName
   */
  @javax.annotation.Nonnull
  public String getMonitorName() {
    return monitorName;
  }

  public void setMonitorName(@javax.annotation.Nonnull String monitorName) {
    this.monitorName = monitorName;
  }


  public BillingLogResponse billedAt(@javax.annotation.Nonnull OffsetDateTime billedAt) {
    this.billedAt = billedAt;
    return this;
  }

  /**
   * Get billedAt
   * @return billedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getBilledAt() {
    return billedAt;
  }

  public void setBilledAt(@javax.annotation.Nonnull OffsetDateTime billedAt) {
    this.billedAt = billedAt;
  }


  public BillingLogResponse numAccounts(@javax.annotation.Nonnull Integer numAccounts) {
    this.numAccounts = numAccounts;
    return this;
  }

  /**
   * Get numAccounts
   * @return numAccounts
   */
  @javax.annotation.Nonnull
  public Integer getNumAccounts() {
    return numAccounts;
  }

  public void setNumAccounts(@javax.annotation.Nonnull Integer numAccounts) {
    this.numAccounts = numAccounts;
  }


  public BillingLogResponse creditsDeducted(@javax.annotation.Nonnull BigDecimal creditsDeducted) {
    this.creditsDeducted = creditsDeducted;
    return this;
  }

  /**
   * Get creditsDeducted
   * @return creditsDeducted
   */
  @javax.annotation.Nonnull
  public BigDecimal getCreditsDeducted() {
    return creditsDeducted;
  }

  public void setCreditsDeducted(@javax.annotation.Nonnull BigDecimal creditsDeducted) {
    this.creditsDeducted = creditsDeducted;
  }


  public BillingLogResponse tierLabel(@javax.annotation.Nonnull String tierLabel) {
    this.tierLabel = tierLabel;
    return this;
  }

  /**
   * Get tierLabel
   * @return tierLabel
   */
  @javax.annotation.Nonnull
  public String getTierLabel() {
    return tierLabel;
  }

  public void setTierLabel(@javax.annotation.Nonnull String tierLabel) {
    this.tierLabel = tierLabel;
  }


  public BillingLogResponse rateApplied(@javax.annotation.Nonnull BigDecimal rateApplied) {
    this.rateApplied = rateApplied;
    return this;
  }

  /**
   * Get rateApplied
   * @return rateApplied
   */
  @javax.annotation.Nonnull
  public BigDecimal getRateApplied() {
    return rateApplied;
  }

  public void setRateApplied(@javax.annotation.Nonnull BigDecimal rateApplied) {
    this.rateApplied = rateApplied;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillingLogResponse billingLogResponse = (BillingLogResponse) o;
    return Objects.equals(this.id, billingLogResponse.id) &&
        Objects.equals(this.monitorId, billingLogResponse.monitorId) &&
        Objects.equals(this.monitorName, billingLogResponse.monitorName) &&
        Objects.equals(this.billedAt, billingLogResponse.billedAt) &&
        Objects.equals(this.numAccounts, billingLogResponse.numAccounts) &&
        Objects.equals(this.creditsDeducted, billingLogResponse.creditsDeducted) &&
        Objects.equals(this.tierLabel, billingLogResponse.tierLabel) &&
        Objects.equals(this.rateApplied, billingLogResponse.rateApplied);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, monitorId, monitorName, billedAt, numAccounts, creditsDeducted, tierLabel, rateApplied);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillingLogResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    monitorId: ").append(toIndentedString(monitorId)).append("\n");
    sb.append("    monitorName: ").append(toIndentedString(monitorName)).append("\n");
    sb.append("    billedAt: ").append(toIndentedString(billedAt)).append("\n");
    sb.append("    numAccounts: ").append(toIndentedString(numAccounts)).append("\n");
    sb.append("    creditsDeducted: ").append(toIndentedString(creditsDeducted)).append("\n");
    sb.append("    tierLabel: ").append(toIndentedString(tierLabel)).append("\n");
    sb.append("    rateApplied: ").append(toIndentedString(rateApplied)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("monitor_id");
    openapiFields.add("monitor_name");
    openapiFields.add("billed_at");
    openapiFields.add("num_accounts");
    openapiFields.add("credits_deducted");
    openapiFields.add("tier_label");
    openapiFields.add("rate_applied");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("monitor_id");
    openapiRequiredFields.add("monitor_name");
    openapiRequiredFields.add("billed_at");
    openapiRequiredFields.add("num_accounts");
    openapiRequiredFields.add("credits_deducted");
    openapiRequiredFields.add("tier_label");
    openapiRequiredFields.add("rate_applied");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BillingLogResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BillingLogResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BillingLogResponse is not found in the empty JSON string", BillingLogResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BillingLogResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BillingLogResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BillingLogResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("monitor_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `monitor_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("monitor_id").toString()));
      }
      if (!jsonObj.get("monitor_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `monitor_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("monitor_name").toString()));
      }
      if (!jsonObj.get("tier_label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tier_label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tier_label").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BillingLogResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BillingLogResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BillingLogResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BillingLogResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<BillingLogResponse>() {
           @Override
           public void write(JsonWriter out, BillingLogResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BillingLogResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BillingLogResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BillingLogResponse
   * @throws IOException if the JSON string is invalid with respect to BillingLogResponse
   */
  public static BillingLogResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BillingLogResponse.class);
  }

  /**
   * Convert an instance of BillingLogResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

