/*
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.scrapebadger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.scrapebadger.client.model.FilterRuleDeliveryLogResponse;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.scrapebadger.client.JSON;

/**
 * Paginated filter rule delivery logs.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class FilterRuleDeliveryLogListResponse {
  public static final String SERIALIZED_NAME_LOGS = "logs";
  @SerializedName(SERIALIZED_NAME_LOGS)
  @javax.annotation.Nonnull
  private List<FilterRuleDeliveryLogResponse> logs = new ArrayList<>();

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  @javax.annotation.Nonnull
  private Integer total;

  public static final String SERIALIZED_NAME_PAGE = "page";
  @SerializedName(SERIALIZED_NAME_PAGE)
  @javax.annotation.Nonnull
  private Integer page;

  public static final String SERIALIZED_NAME_PAGE_SIZE = "page_size";
  @SerializedName(SERIALIZED_NAME_PAGE_SIZE)
  @javax.annotation.Nonnull
  private Integer pageSize;

  public FilterRuleDeliveryLogListResponse() {
  }

  public FilterRuleDeliveryLogListResponse logs(@javax.annotation.Nonnull List<FilterRuleDeliveryLogResponse> logs) {
    this.logs = logs;
    return this;
  }

  public FilterRuleDeliveryLogListResponse addLogsItem(FilterRuleDeliveryLogResponse logsItem) {
    if (this.logs == null) {
      this.logs = new ArrayList<>();
    }
    this.logs.add(logsItem);
    return this;
  }

  /**
   * Get logs
   * @return logs
   */
  @javax.annotation.Nonnull
  public List<FilterRuleDeliveryLogResponse> getLogs() {
    return logs;
  }

  public void setLogs(@javax.annotation.Nonnull List<FilterRuleDeliveryLogResponse> logs) {
    this.logs = logs;
  }


  public FilterRuleDeliveryLogListResponse total(@javax.annotation.Nonnull Integer total) {
    this.total = total;
    return this;
  }

  /**
   * Get total
   * @return total
   */
  @javax.annotation.Nonnull
  public Integer getTotal() {
    return total;
  }

  public void setTotal(@javax.annotation.Nonnull Integer total) {
    this.total = total;
  }


  public FilterRuleDeliveryLogListResponse page(@javax.annotation.Nonnull Integer page) {
    this.page = page;
    return this;
  }

  /**
   * Get page
   * @return page
   */
  @javax.annotation.Nonnull
  public Integer getPage() {
    return page;
  }

  public void setPage(@javax.annotation.Nonnull Integer page) {
    this.page = page;
  }


  public FilterRuleDeliveryLogListResponse pageSize(@javax.annotation.Nonnull Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

  /**
   * Get pageSize
   * @return pageSize
   */
  @javax.annotation.Nonnull
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(@javax.annotation.Nonnull Integer pageSize) {
    this.pageSize = pageSize;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilterRuleDeliveryLogListResponse filterRuleDeliveryLogListResponse = (FilterRuleDeliveryLogListResponse) o;
    return Objects.equals(this.logs, filterRuleDeliveryLogListResponse.logs) &&
        Objects.equals(this.total, filterRuleDeliveryLogListResponse.total) &&
        Objects.equals(this.page, filterRuleDeliveryLogListResponse.page) &&
        Objects.equals(this.pageSize, filterRuleDeliveryLogListResponse.pageSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(logs, total, page, pageSize);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilterRuleDeliveryLogListResponse {\n");
    sb.append("    logs: ").append(toIndentedString(logs)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("logs");
    openapiFields.add("total");
    openapiFields.add("page");
    openapiFields.add("page_size");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("logs");
    openapiRequiredFields.add("total");
    openapiRequiredFields.add("page");
    openapiRequiredFields.add("page_size");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FilterRuleDeliveryLogListResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FilterRuleDeliveryLogListResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FilterRuleDeliveryLogListResponse is not found in the empty JSON string", FilterRuleDeliveryLogListResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FilterRuleDeliveryLogListResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `FilterRuleDeliveryLogListResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : FilterRuleDeliveryLogListResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("logs").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `logs` to be an array in the JSON string but got `%s`", jsonObj.get("logs").toString()));
      }

      JsonArray jsonArraylogs = jsonObj.getAsJsonArray("logs");
      // validate the required field `logs` (array)
      for (int i = 0; i < jsonArraylogs.size(); i++) {
        FilterRuleDeliveryLogResponse.validateJsonElement(jsonArraylogs.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FilterRuleDeliveryLogListResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FilterRuleDeliveryLogListResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FilterRuleDeliveryLogListResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FilterRuleDeliveryLogListResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<FilterRuleDeliveryLogListResponse>() {
           @Override
           public void write(JsonWriter out, FilterRuleDeliveryLogListResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FilterRuleDeliveryLogListResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FilterRuleDeliveryLogListResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FilterRuleDeliveryLogListResponse
   * @throws IOException if the JSON string is invalid with respect to FilterRuleDeliveryLogListResponse
   */
  public static FilterRuleDeliveryLogListResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FilterRuleDeliveryLogListResponse.class);
  }

  /**
   * Convert an instance of FilterRuleDeliveryLogListResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

