/*
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.scrapebadger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.scrapebadger.client.JSON;

/**
 * ScreenshotRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ScreenshotRequest {
  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  @javax.annotation.Nonnull
  private String url;

  public static final String SERIALIZED_NAME_WAIT_FOR = "wait_for";
  @SerializedName(SERIALIZED_NAME_WAIT_FOR)
  @javax.annotation.Nullable
  private String waitFor;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  @javax.annotation.Nullable
  private String country;

  /**
   * Proxy pool: simple, premium or ultra.
   */
  @JsonAdapter(ProxyTierEnum.Adapter.class)
  public enum ProxyTierEnum {
    SIMPLE("simple"),
    
    PREMIUM("premium"),
    
    ULTRA("ultra");

    private String value;

    ProxyTierEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ProxyTierEnum fromValue(String value) {
      for (ProxyTierEnum b : ProxyTierEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ProxyTierEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ProxyTierEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ProxyTierEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ProxyTierEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ProxyTierEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_PROXY_TIER = "proxy_tier";
  @SerializedName(SERIALIZED_NAME_PROXY_TIER)
  @javax.annotation.Nullable
  private ProxyTierEnum proxyTier = ProxyTierEnum.SIMPLE;

  public static final String SERIALIZED_NAME_FULL_PAGE = "full_page";
  @SerializedName(SERIALIZED_NAME_FULL_PAGE)
  @javax.annotation.Nullable
  private Boolean fullPage = false;

  public static final String SERIALIZED_NAME_WIDTH = "width";
  @SerializedName(SERIALIZED_NAME_WIDTH)
  @javax.annotation.Nullable
  private Integer width;

  public static final String SERIALIZED_NAME_HEIGHT = "height";
  @SerializedName(SERIALIZED_NAME_HEIGHT)
  @javax.annotation.Nullable
  private Integer height;

  public ScreenshotRequest() {
  }

  public ScreenshotRequest url(@javax.annotation.Nonnull String url) {
    this.url = url;
    return this;
  }

  /**
   * The page to fetch.
   * @return url
   */
  @javax.annotation.Nonnull
  public String getUrl() {
    return url;
  }

  public void setUrl(@javax.annotation.Nonnull String url) {
    this.url = url;
  }


  public ScreenshotRequest waitFor(@javax.annotation.Nullable String waitFor) {
    this.waitFor = waitFor;
    return this;
  }

  /**
   * Get waitFor
   * @return waitFor
   */
  @javax.annotation.Nullable
  public String getWaitFor() {
    return waitFor;
  }

  public void setWaitFor(@javax.annotation.Nullable String waitFor) {
    this.waitFor = waitFor;
  }


  public ScreenshotRequest country(@javax.annotation.Nullable String country) {
    this.country = country;
    return this;
  }

  /**
   * Get country
   * @return country
   */
  @javax.annotation.Nullable
  public String getCountry() {
    return country;
  }

  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }


  public ScreenshotRequest proxyTier(@javax.annotation.Nullable ProxyTierEnum proxyTier) {
    this.proxyTier = proxyTier;
    return this;
  }

  /**
   * Proxy pool: simple, premium or ultra.
   * @return proxyTier
   */
  @javax.annotation.Nullable
  public ProxyTierEnum getProxyTier() {
    return proxyTier;
  }

  public void setProxyTier(@javax.annotation.Nullable ProxyTierEnum proxyTier) {
    this.proxyTier = proxyTier;
  }


  public ScreenshotRequest fullPage(@javax.annotation.Nullable Boolean fullPage) {
    this.fullPage = fullPage;
    return this;
  }

  /**
   * Capture the whole scrollable page instead of the viewport.
   * @return fullPage
   */
  @javax.annotation.Nullable
  public Boolean getFullPage() {
    return fullPage;
  }

  public void setFullPage(@javax.annotation.Nullable Boolean fullPage) {
    this.fullPage = fullPage;
  }


  public ScreenshotRequest width(@javax.annotation.Nullable Integer width) {
    this.width = width;
    return this;
  }

  /**
   * Get width
   * minimum: 320
   * maximum: 3840
   * @return width
   */
  @javax.annotation.Nullable
  public Integer getWidth() {
    return width;
  }

  public void setWidth(@javax.annotation.Nullable Integer width) {
    this.width = width;
  }


  public ScreenshotRequest height(@javax.annotation.Nullable Integer height) {
    this.height = height;
    return this;
  }

  /**
   * Get height
   * minimum: 240
   * maximum: 4320
   * @return height
   */
  @javax.annotation.Nullable
  public Integer getHeight() {
    return height;
  }

  public void setHeight(@javax.annotation.Nullable Integer height) {
    this.height = height;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ScreenshotRequest instance itself
   */
  public ScreenshotRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScreenshotRequest screenshotRequest = (ScreenshotRequest) o;
    return Objects.equals(this.url, screenshotRequest.url) &&
        Objects.equals(this.waitFor, screenshotRequest.waitFor) &&
        Objects.equals(this.country, screenshotRequest.country) &&
        Objects.equals(this.proxyTier, screenshotRequest.proxyTier) &&
        Objects.equals(this.fullPage, screenshotRequest.fullPage) &&
        Objects.equals(this.width, screenshotRequest.width) &&
        Objects.equals(this.height, screenshotRequest.height)&&
        Objects.equals(this.additionalProperties, screenshotRequest.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, waitFor, country, proxyTier, fullPage, width, height, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScreenshotRequest {\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    waitFor: ").append(toIndentedString(waitFor)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    proxyTier: ").append(toIndentedString(proxyTier)).append("\n");
    sb.append("    fullPage: ").append(toIndentedString(fullPage)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("url");
    openapiFields.add("wait_for");
    openapiFields.add("country");
    openapiFields.add("proxy_tier");
    openapiFields.add("full_page");
    openapiFields.add("width");
    openapiFields.add("height");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("url");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ScreenshotRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ScreenshotRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ScreenshotRequest is not found in the empty JSON string", ScreenshotRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ScreenshotRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
      if ((jsonObj.get("wait_for") != null && !jsonObj.get("wait_for").isJsonNull()) && !jsonObj.get("wait_for").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `wait_for` to be a primitive type in the JSON string but got `%s`", jsonObj.get("wait_for").toString()));
      }
      if ((jsonObj.get("country") != null && !jsonObj.get("country").isJsonNull()) && !jsonObj.get("country").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `country` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country").toString()));
      }
      if ((jsonObj.get("proxy_tier") != null && !jsonObj.get("proxy_tier").isJsonNull()) && !jsonObj.get("proxy_tier").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `proxy_tier` to be a primitive type in the JSON string but got `%s`", jsonObj.get("proxy_tier").toString()));
      }
      // validate the optional field `proxy_tier`
      if (jsonObj.get("proxy_tier") != null && !jsonObj.get("proxy_tier").isJsonNull()) {
        ProxyTierEnum.validateJsonElement(jsonObj.get("proxy_tier"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ScreenshotRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ScreenshotRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ScreenshotRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ScreenshotRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ScreenshotRequest>() {
           @Override
           public void write(JsonWriter out, ScreenshotRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ScreenshotRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             ScreenshotRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ScreenshotRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ScreenshotRequest
   * @throws IOException if the JSON string is invalid with respect to ScreenshotRequest
   */
  public static ScreenshotRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ScreenshotRequest.class);
  }

  /**
   * Convert an instance of ScreenshotRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

