/*
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.scrapebadger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.scrapebadger.client.JSON;

/**
 * Tweet delivery log entry.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class TweetDeliveryLogResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_MONITOR_ID = "monitor_id";
  @SerializedName(SERIALIZED_NAME_MONITOR_ID)
  @javax.annotation.Nonnull
  private String monitorId;

  public static final String SERIALIZED_NAME_MONITOR_NAME = "monitor_name";
  @SerializedName(SERIALIZED_NAME_MONITOR_NAME)
  @javax.annotation.Nonnull
  private String monitorName;

  public static final String SERIALIZED_NAME_TWEET_ID = "tweet_id";
  @SerializedName(SERIALIZED_NAME_TWEET_ID)
  @javax.annotation.Nonnull
  private String tweetId;

  public static final String SERIALIZED_NAME_AUTHOR_USERNAME = "author_username";
  @SerializedName(SERIALIZED_NAME_AUTHOR_USERNAME)
  @javax.annotation.Nonnull
  private String authorUsername;

  public static final String SERIALIZED_NAME_TWEET_TEXT_PREVIEW = "tweet_text_preview";
  @SerializedName(SERIALIZED_NAME_TWEET_TEXT_PREVIEW)
  @javax.annotation.Nullable
  private String tweetTextPreview;

  public static final String SERIALIZED_NAME_TWEET_URL = "tweet_url";
  @SerializedName(SERIALIZED_NAME_TWEET_URL)
  @javax.annotation.Nonnull
  private String tweetUrl;

  public static final String SERIALIZED_NAME_TWEET_PUBLISHED_AT = "tweet_published_at";
  @SerializedName(SERIALIZED_NAME_TWEET_PUBLISHED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime tweetPublishedAt;

  public static final String SERIALIZED_NAME_DETECTED_AT = "detected_at";
  @SerializedName(SERIALIZED_NAME_DETECTED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime detectedAt;

  public static final String SERIALIZED_NAME_LATENCY_MS = "latency_ms";
  @SerializedName(SERIALIZED_NAME_LATENCY_MS)
  @javax.annotation.Nonnull
  private Integer latencyMs;

  public static final String SERIALIZED_NAME_LATENCY_BADGE = "latency_badge";
  @SerializedName(SERIALIZED_NAME_LATENCY_BADGE)
  @javax.annotation.Nonnull
  private String latencyBadge;

  public static final String SERIALIZED_NAME_DELIVERY_STATUS = "delivery_status";
  @SerializedName(SERIALIZED_NAME_DELIVERY_STATUS)
  @javax.annotation.Nonnull
  private String deliveryStatus;

  public static final String SERIALIZED_NAME_WEBHOOK_STATUS_CODE = "webhook_status_code";
  @SerializedName(SERIALIZED_NAME_WEBHOOK_STATUS_CODE)
  @javax.annotation.Nullable
  private Integer webhookStatusCode;

  public static final String SERIALIZED_NAME_WEBHOOK_ATTEMPTS = "webhook_attempts";
  @SerializedName(SERIALIZED_NAME_WEBHOOK_ATTEMPTS)
  @javax.annotation.Nonnull
  private Integer webhookAttempts;

  public TweetDeliveryLogResponse() {
  }

  public TweetDeliveryLogResponse id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public TweetDeliveryLogResponse monitorId(@javax.annotation.Nonnull String monitorId) {
    this.monitorId = monitorId;
    return this;
  }

  /**
   * Get monitorId
   * @return monitorId
   */
  @javax.annotation.Nonnull
  public String getMonitorId() {
    return monitorId;
  }

  public void setMonitorId(@javax.annotation.Nonnull String monitorId) {
    this.monitorId = monitorId;
  }


  public TweetDeliveryLogResponse monitorName(@javax.annotation.Nonnull String monitorName) {
    this.monitorName = monitorName;
    return this;
  }

  /**
   * Get monitorName
   * @return monitorName
   */
  @javax.annotation.Nonnull
  public String getMonitorName() {
    return monitorName;
  }

  public void setMonitorName(@javax.annotation.Nonnull String monitorName) {
    this.monitorName = monitorName;
  }


  public TweetDeliveryLogResponse tweetId(@javax.annotation.Nonnull String tweetId) {
    this.tweetId = tweetId;
    return this;
  }

  /**
   * Get tweetId
   * @return tweetId
   */
  @javax.annotation.Nonnull
  public String getTweetId() {
    return tweetId;
  }

  public void setTweetId(@javax.annotation.Nonnull String tweetId) {
    this.tweetId = tweetId;
  }


  public TweetDeliveryLogResponse authorUsername(@javax.annotation.Nonnull String authorUsername) {
    this.authorUsername = authorUsername;
    return this;
  }

  /**
   * Get authorUsername
   * @return authorUsername
   */
  @javax.annotation.Nonnull
  public String getAuthorUsername() {
    return authorUsername;
  }

  public void setAuthorUsername(@javax.annotation.Nonnull String authorUsername) {
    this.authorUsername = authorUsername;
  }


  public TweetDeliveryLogResponse tweetTextPreview(@javax.annotation.Nullable String tweetTextPreview) {
    this.tweetTextPreview = tweetTextPreview;
    return this;
  }

  /**
   * Get tweetTextPreview
   * @return tweetTextPreview
   */
  @javax.annotation.Nullable
  public String getTweetTextPreview() {
    return tweetTextPreview;
  }

  public void setTweetTextPreview(@javax.annotation.Nullable String tweetTextPreview) {
    this.tweetTextPreview = tweetTextPreview;
  }


  public TweetDeliveryLogResponse tweetUrl(@javax.annotation.Nonnull String tweetUrl) {
    this.tweetUrl = tweetUrl;
    return this;
  }

  /**
   * Get tweetUrl
   * @return tweetUrl
   */
  @javax.annotation.Nonnull
  public String getTweetUrl() {
    return tweetUrl;
  }

  public void setTweetUrl(@javax.annotation.Nonnull String tweetUrl) {
    this.tweetUrl = tweetUrl;
  }


  public TweetDeliveryLogResponse tweetPublishedAt(@javax.annotation.Nonnull OffsetDateTime tweetPublishedAt) {
    this.tweetPublishedAt = tweetPublishedAt;
    return this;
  }

  /**
   * Get tweetPublishedAt
   * @return tweetPublishedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getTweetPublishedAt() {
    return tweetPublishedAt;
  }

  public void setTweetPublishedAt(@javax.annotation.Nonnull OffsetDateTime tweetPublishedAt) {
    this.tweetPublishedAt = tweetPublishedAt;
  }


  public TweetDeliveryLogResponse detectedAt(@javax.annotation.Nonnull OffsetDateTime detectedAt) {
    this.detectedAt = detectedAt;
    return this;
  }

  /**
   * Get detectedAt
   * @return detectedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getDetectedAt() {
    return detectedAt;
  }

  public void setDetectedAt(@javax.annotation.Nonnull OffsetDateTime detectedAt) {
    this.detectedAt = detectedAt;
  }


  public TweetDeliveryLogResponse latencyMs(@javax.annotation.Nonnull Integer latencyMs) {
    this.latencyMs = latencyMs;
    return this;
  }

  /**
   * Get latencyMs
   * @return latencyMs
   */
  @javax.annotation.Nonnull
  public Integer getLatencyMs() {
    return latencyMs;
  }

  public void setLatencyMs(@javax.annotation.Nonnull Integer latencyMs) {
    this.latencyMs = latencyMs;
  }


  public TweetDeliveryLogResponse latencyBadge(@javax.annotation.Nonnull String latencyBadge) {
    this.latencyBadge = latencyBadge;
    return this;
  }

  /**
   * Get latencyBadge
   * @return latencyBadge
   */
  @javax.annotation.Nonnull
  public String getLatencyBadge() {
    return latencyBadge;
  }

  public void setLatencyBadge(@javax.annotation.Nonnull String latencyBadge) {
    this.latencyBadge = latencyBadge;
  }


  public TweetDeliveryLogResponse deliveryStatus(@javax.annotation.Nonnull String deliveryStatus) {
    this.deliveryStatus = deliveryStatus;
    return this;
  }

  /**
   * Get deliveryStatus
   * @return deliveryStatus
   */
  @javax.annotation.Nonnull
  public String getDeliveryStatus() {
    return deliveryStatus;
  }

  public void setDeliveryStatus(@javax.annotation.Nonnull String deliveryStatus) {
    this.deliveryStatus = deliveryStatus;
  }


  public TweetDeliveryLogResponse webhookStatusCode(@javax.annotation.Nullable Integer webhookStatusCode) {
    this.webhookStatusCode = webhookStatusCode;
    return this;
  }

  /**
   * Get webhookStatusCode
   * @return webhookStatusCode
   */
  @javax.annotation.Nullable
  public Integer getWebhookStatusCode() {
    return webhookStatusCode;
  }

  public void setWebhookStatusCode(@javax.annotation.Nullable Integer webhookStatusCode) {
    this.webhookStatusCode = webhookStatusCode;
  }


  public TweetDeliveryLogResponse webhookAttempts(@javax.annotation.Nonnull Integer webhookAttempts) {
    this.webhookAttempts = webhookAttempts;
    return this;
  }

  /**
   * Get webhookAttempts
   * @return webhookAttempts
   */
  @javax.annotation.Nonnull
  public Integer getWebhookAttempts() {
    return webhookAttempts;
  }

  public void setWebhookAttempts(@javax.annotation.Nonnull Integer webhookAttempts) {
    this.webhookAttempts = webhookAttempts;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TweetDeliveryLogResponse tweetDeliveryLogResponse = (TweetDeliveryLogResponse) o;
    return Objects.equals(this.id, tweetDeliveryLogResponse.id) &&
        Objects.equals(this.monitorId, tweetDeliveryLogResponse.monitorId) &&
        Objects.equals(this.monitorName, tweetDeliveryLogResponse.monitorName) &&
        Objects.equals(this.tweetId, tweetDeliveryLogResponse.tweetId) &&
        Objects.equals(this.authorUsername, tweetDeliveryLogResponse.authorUsername) &&
        Objects.equals(this.tweetTextPreview, tweetDeliveryLogResponse.tweetTextPreview) &&
        Objects.equals(this.tweetUrl, tweetDeliveryLogResponse.tweetUrl) &&
        Objects.equals(this.tweetPublishedAt, tweetDeliveryLogResponse.tweetPublishedAt) &&
        Objects.equals(this.detectedAt, tweetDeliveryLogResponse.detectedAt) &&
        Objects.equals(this.latencyMs, tweetDeliveryLogResponse.latencyMs) &&
        Objects.equals(this.latencyBadge, tweetDeliveryLogResponse.latencyBadge) &&
        Objects.equals(this.deliveryStatus, tweetDeliveryLogResponse.deliveryStatus) &&
        Objects.equals(this.webhookStatusCode, tweetDeliveryLogResponse.webhookStatusCode) &&
        Objects.equals(this.webhookAttempts, tweetDeliveryLogResponse.webhookAttempts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, monitorId, monitorName, tweetId, authorUsername, tweetTextPreview, tweetUrl, tweetPublishedAt, detectedAt, latencyMs, latencyBadge, deliveryStatus, webhookStatusCode, webhookAttempts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TweetDeliveryLogResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    monitorId: ").append(toIndentedString(monitorId)).append("\n");
    sb.append("    monitorName: ").append(toIndentedString(monitorName)).append("\n");
    sb.append("    tweetId: ").append(toIndentedString(tweetId)).append("\n");
    sb.append("    authorUsername: ").append(toIndentedString(authorUsername)).append("\n");
    sb.append("    tweetTextPreview: ").append(toIndentedString(tweetTextPreview)).append("\n");
    sb.append("    tweetUrl: ").append(toIndentedString(tweetUrl)).append("\n");
    sb.append("    tweetPublishedAt: ").append(toIndentedString(tweetPublishedAt)).append("\n");
    sb.append("    detectedAt: ").append(toIndentedString(detectedAt)).append("\n");
    sb.append("    latencyMs: ").append(toIndentedString(latencyMs)).append("\n");
    sb.append("    latencyBadge: ").append(toIndentedString(latencyBadge)).append("\n");
    sb.append("    deliveryStatus: ").append(toIndentedString(deliveryStatus)).append("\n");
    sb.append("    webhookStatusCode: ").append(toIndentedString(webhookStatusCode)).append("\n");
    sb.append("    webhookAttempts: ").append(toIndentedString(webhookAttempts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("monitor_id");
    openapiFields.add("monitor_name");
    openapiFields.add("tweet_id");
    openapiFields.add("author_username");
    openapiFields.add("tweet_text_preview");
    openapiFields.add("tweet_url");
    openapiFields.add("tweet_published_at");
    openapiFields.add("detected_at");
    openapiFields.add("latency_ms");
    openapiFields.add("latency_badge");
    openapiFields.add("delivery_status");
    openapiFields.add("webhook_status_code");
    openapiFields.add("webhook_attempts");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("monitor_id");
    openapiRequiredFields.add("monitor_name");
    openapiRequiredFields.add("tweet_id");
    openapiRequiredFields.add("author_username");
    openapiRequiredFields.add("tweet_text_preview");
    openapiRequiredFields.add("tweet_url");
    openapiRequiredFields.add("tweet_published_at");
    openapiRequiredFields.add("detected_at");
    openapiRequiredFields.add("latency_ms");
    openapiRequiredFields.add("latency_badge");
    openapiRequiredFields.add("delivery_status");
    openapiRequiredFields.add("webhook_status_code");
    openapiRequiredFields.add("webhook_attempts");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TweetDeliveryLogResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TweetDeliveryLogResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TweetDeliveryLogResponse is not found in the empty JSON string", TweetDeliveryLogResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TweetDeliveryLogResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TweetDeliveryLogResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TweetDeliveryLogResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("monitor_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `monitor_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("monitor_id").toString()));
      }
      if (!jsonObj.get("monitor_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `monitor_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("monitor_name").toString()));
      }
      if (!jsonObj.get("tweet_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tweet_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tweet_id").toString()));
      }
      if (!jsonObj.get("author_username").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `author_username` to be a primitive type in the JSON string but got `%s`", jsonObj.get("author_username").toString()));
      }
      if ((jsonObj.get("tweet_text_preview") != null && !jsonObj.get("tweet_text_preview").isJsonNull()) && !jsonObj.get("tweet_text_preview").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tweet_text_preview` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tweet_text_preview").toString()));
      }
      if (!jsonObj.get("tweet_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tweet_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tweet_url").toString()));
      }
      if (!jsonObj.get("latency_badge").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `latency_badge` to be a primitive type in the JSON string but got `%s`", jsonObj.get("latency_badge").toString()));
      }
      if (!jsonObj.get("delivery_status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `delivery_status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("delivery_status").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TweetDeliveryLogResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TweetDeliveryLogResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TweetDeliveryLogResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TweetDeliveryLogResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<TweetDeliveryLogResponse>() {
           @Override
           public void write(JsonWriter out, TweetDeliveryLogResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TweetDeliveryLogResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TweetDeliveryLogResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TweetDeliveryLogResponse
   * @throws IOException if the JSON string is invalid with respect to TweetDeliveryLogResponse
   */
  public static TweetDeliveryLogResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TweetDeliveryLogResponse.class);
  }

  /**
   * Convert an instance of TweetDeliveryLogResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

