/*
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.scrapebadger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.scrapebadger.client.JSON;

/**
 * One item photo.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class VintedPhoto {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private Integer id;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  @javax.annotation.Nonnull
  private String url;

  public static final String SERIALIZED_NAME_DOMINANT_COLOR = "dominant_color";
  @SerializedName(SERIALIZED_NAME_DOMINANT_COLOR)
  @javax.annotation.Nullable
  private String dominantColor;

  public static final String SERIALIZED_NAME_IS_MAIN = "is_main";
  @SerializedName(SERIALIZED_NAME_IS_MAIN)
  @javax.annotation.Nullable
  private Boolean isMain = false;

  public static final String SERIALIZED_NAME_WIDTH = "width";
  @SerializedName(SERIALIZED_NAME_WIDTH)
  @javax.annotation.Nullable
  private Integer width;

  public static final String SERIALIZED_NAME_HEIGHT = "height";
  @SerializedName(SERIALIZED_NAME_HEIGHT)
  @javax.annotation.Nullable
  private Integer height;

  public static final String SERIALIZED_NAME_FULL_SIZE_URL = "full_size_url";
  @SerializedName(SERIALIZED_NAME_FULL_SIZE_URL)
  @javax.annotation.Nullable
  private String fullSizeUrl;

  public VintedPhoto() {
  }

  public VintedPhoto id(@javax.annotation.Nonnull Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull Integer id) {
    this.id = id;
  }


  public VintedPhoto url(@javax.annotation.Nonnull String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @javax.annotation.Nonnull
  public String getUrl() {
    return url;
  }

  public void setUrl(@javax.annotation.Nonnull String url) {
    this.url = url;
  }


  public VintedPhoto dominantColor(@javax.annotation.Nullable String dominantColor) {
    this.dominantColor = dominantColor;
    return this;
  }

  /**
   * Get dominantColor
   * @return dominantColor
   */
  @javax.annotation.Nullable
  public String getDominantColor() {
    return dominantColor;
  }

  public void setDominantColor(@javax.annotation.Nullable String dominantColor) {
    this.dominantColor = dominantColor;
  }


  public VintedPhoto isMain(@javax.annotation.Nullable Boolean isMain) {
    this.isMain = isMain;
    return this;
  }

  /**
   * Get isMain
   * @return isMain
   */
  @javax.annotation.Nullable
  public Boolean getIsMain() {
    return isMain;
  }

  public void setIsMain(@javax.annotation.Nullable Boolean isMain) {
    this.isMain = isMain;
  }


  public VintedPhoto width(@javax.annotation.Nullable Integer width) {
    this.width = width;
    return this;
  }

  /**
   * Get width
   * @return width
   */
  @javax.annotation.Nullable
  public Integer getWidth() {
    return width;
  }

  public void setWidth(@javax.annotation.Nullable Integer width) {
    this.width = width;
  }


  public VintedPhoto height(@javax.annotation.Nullable Integer height) {
    this.height = height;
    return this;
  }

  /**
   * Get height
   * @return height
   */
  @javax.annotation.Nullable
  public Integer getHeight() {
    return height;
  }

  public void setHeight(@javax.annotation.Nullable Integer height) {
    this.height = height;
  }


  public VintedPhoto fullSizeUrl(@javax.annotation.Nullable String fullSizeUrl) {
    this.fullSizeUrl = fullSizeUrl;
    return this;
  }

  /**
   * Get fullSizeUrl
   * @return fullSizeUrl
   */
  @javax.annotation.Nullable
  public String getFullSizeUrl() {
    return fullSizeUrl;
  }

  public void setFullSizeUrl(@javax.annotation.Nullable String fullSizeUrl) {
    this.fullSizeUrl = fullSizeUrl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VintedPhoto vintedPhoto = (VintedPhoto) o;
    return Objects.equals(this.id, vintedPhoto.id) &&
        Objects.equals(this.url, vintedPhoto.url) &&
        Objects.equals(this.dominantColor, vintedPhoto.dominantColor) &&
        Objects.equals(this.isMain, vintedPhoto.isMain) &&
        Objects.equals(this.width, vintedPhoto.width) &&
        Objects.equals(this.height, vintedPhoto.height) &&
        Objects.equals(this.fullSizeUrl, vintedPhoto.fullSizeUrl);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, dominantColor, isMain, width, height, fullSizeUrl);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VintedPhoto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    dominantColor: ").append(toIndentedString(dominantColor)).append("\n");
    sb.append("    isMain: ").append(toIndentedString(isMain)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    fullSizeUrl: ").append(toIndentedString(fullSizeUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("url");
    openapiFields.add("dominant_color");
    openapiFields.add("is_main");
    openapiFields.add("width");
    openapiFields.add("height");
    openapiFields.add("full_size_url");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("url");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to VintedPhoto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!VintedPhoto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in VintedPhoto is not found in the empty JSON string", VintedPhoto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!VintedPhoto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `VintedPhoto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : VintedPhoto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
      if ((jsonObj.get("dominant_color") != null && !jsonObj.get("dominant_color").isJsonNull()) && !jsonObj.get("dominant_color").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dominant_color` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dominant_color").toString()));
      }
      if ((jsonObj.get("full_size_url") != null && !jsonObj.get("full_size_url").isJsonNull()) && !jsonObj.get("full_size_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `full_size_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("full_size_url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VintedPhoto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VintedPhoto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VintedPhoto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VintedPhoto.class));

       return (TypeAdapter<T>) new TypeAdapter<VintedPhoto>() {
           @Override
           public void write(JsonWriter out, VintedPhoto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public VintedPhoto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of VintedPhoto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of VintedPhoto
   * @throws IOException if the JSON string is invalid with respect to VintedPhoto
   */
  public static VintedPhoto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VintedPhoto.class);
  }

  /**
   * Convert an instance of VintedPhoto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

