/*
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.scrapebadger.client.api;

import com.scrapebadger.client.ApiCallback;
import com.scrapebadger.client.ApiClient;
import com.scrapebadger.client.ApiException;
import com.scrapebadger.client.ApiResponse;
import com.scrapebadger.client.Configuration;
import com.scrapebadger.client.Pair;
import com.scrapebadger.client.ProgressRequestBody;
import com.scrapebadger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.scrapebadger.client.model.HTTPValidationError;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LinkedInApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public LinkedInApi() {
        this(Configuration.getDefaultApiClient());
    }

    public LinkedInApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for linkedinGetACompanySJobPostings
     * @param companyId  (required)
     * @param start Pagination offset (0, 25, 50, ...) (optional, default to 0)
     * @param country Residential proxy country (optional, default to us)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinGetACompanySJobPostingsCall(String companyId, Integer start, String country, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/linkedin/companies/{company_id}/jobs"
            .replace("{" + "company_id" + "}", localVarApiClient.escapeString(companyId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (start != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("start", start));
        }

        if (country != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("country", country));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call linkedinGetACompanySJobPostingsValidateBeforeCall(String companyId, Integer start, String country, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'companyId' is set
        if (companyId == null) {
            throw new ApiException("Missing the required parameter 'companyId' when calling linkedinGetACompanySJobPostings(Async)");
        }

        return linkedinGetACompanySJobPostingsCall(companyId, start, country, _callback);

    }

    /**
     * Get a company&#39;s job postings
     * Public job postings for a company (numeric company id from the company endpoint).
     * @param companyId  (required)
     * @param start Pagination offset (0, 25, 50, ...) (optional, default to 0)
     * @param country Residential proxy country (optional, default to us)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object linkedinGetACompanySJobPostings(String companyId, Integer start, String country) throws ApiException {
        ApiResponse<Object> localVarResp = linkedinGetACompanySJobPostingsWithHttpInfo(companyId, start, country);
        return localVarResp.getData();
    }

    /**
     * Get a company&#39;s job postings
     * Public job postings for a company (numeric company id from the company endpoint).
     * @param companyId  (required)
     * @param start Pagination offset (0, 25, 50, ...) (optional, default to 0)
     * @param country Residential proxy country (optional, default to us)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> linkedinGetACompanySJobPostingsWithHttpInfo(String companyId, Integer start, String country) throws ApiException {
        okhttp3.Call localVarCall = linkedinGetACompanySJobPostingsValidateBeforeCall(companyId, start, country, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get a company&#39;s job postings (asynchronously)
     * Public job postings for a company (numeric company id from the company endpoint).
     * @param companyId  (required)
     * @param start Pagination offset (0, 25, 50, ...) (optional, default to 0)
     * @param country Residential proxy country (optional, default to us)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinGetACompanySJobPostingsAsync(String companyId, Integer start, String country, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = linkedinGetACompanySJobPostingsValidateBeforeCall(companyId, start, country, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for linkedinGetACourse
     * @param courseSlug  (required)
     * @param country Residential proxy country (optional, default to us)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinGetACourseCall(String courseSlug, String country, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/linkedin/learning/{course_slug}"
            .replace("{" + "course_slug" + "}", localVarApiClient.escapeString(courseSlug.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (country != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("country", country));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call linkedinGetACourseValidateBeforeCall(String courseSlug, String country, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'courseSlug' is set
        if (courseSlug == null) {
            throw new ApiException("Missing the required parameter 'courseSlug' when calling linkedinGetACourse(Async)");
        }

        return linkedinGetACourseCall(courseSlug, country, _callback);

    }

    /**
     * Get a course
     * A public LinkedIn Learning course — provider, workload, instructors, rating.
     * @param courseSlug  (required)
     * @param country Residential proxy country (optional, default to us)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object linkedinGetACourse(String courseSlug, String country) throws ApiException {
        ApiResponse<Object> localVarResp = linkedinGetACourseWithHttpInfo(courseSlug, country);
        return localVarResp.getData();
    }

    /**
     * Get a course
     * A public LinkedIn Learning course — provider, workload, instructors, rating.
     * @param courseSlug  (required)
     * @param country Residential proxy country (optional, default to us)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> linkedinGetACourseWithHttpInfo(String courseSlug, String country) throws ApiException {
        okhttp3.Call localVarCall = linkedinGetACourseValidateBeforeCall(courseSlug, country, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get a course (asynchronously)
     * A public LinkedIn Learning course — provider, workload, instructors, rating.
     * @param courseSlug  (required)
     * @param country Residential proxy country (optional, default to us)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinGetACourseAsync(String courseSlug, String country, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = linkedinGetACourseValidateBeforeCall(courseSlug, country, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for linkedinGetAPublicArticle
     * @param articleSlug  (required)
     * @param country Residential proxy country (optional, default to us)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinGetAPublicArticleCall(String articleSlug, String country, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/linkedin/articles/{article_slug}"
            .replace("{" + "article_slug" + "}", localVarApiClient.escapeString(articleSlug.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (country != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("country", country));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call linkedinGetAPublicArticleValidateBeforeCall(String articleSlug, String country, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'articleSlug' is set
        if (articleSlug == null) {
            throw new ApiException("Missing the required parameter 'articleSlug' when calling linkedinGetAPublicArticle(Async)");
        }

        return linkedinGetAPublicArticleCall(articleSlug, country, _callback);

    }

    /**
     * Get a public article
     * A public Pulse article — title, body, author, reactions (JSON-LD).
     * @param articleSlug  (required)
     * @param country Residential proxy country (optional, default to us)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object linkedinGetAPublicArticle(String articleSlug, String country) throws ApiException {
        ApiResponse<Object> localVarResp = linkedinGetAPublicArticleWithHttpInfo(articleSlug, country);
        return localVarResp.getData();
    }

    /**
     * Get a public article
     * A public Pulse article — title, body, author, reactions (JSON-LD).
     * @param articleSlug  (required)
     * @param country Residential proxy country (optional, default to us)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> linkedinGetAPublicArticleWithHttpInfo(String articleSlug, String country) throws ApiException {
        okhttp3.Call localVarCall = linkedinGetAPublicArticleValidateBeforeCall(articleSlug, country, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get a public article (asynchronously)
     * A public Pulse article — title, body, author, reactions (JSON-LD).
     * @param articleSlug  (required)
     * @param country Residential proxy country (optional, default to us)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinGetAPublicArticleAsync(String articleSlug, String country, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = linkedinGetAPublicArticleValidateBeforeCall(articleSlug, country, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for linkedinGetAPublicPost
     * @param postSlug  (required)
     * @param country Residential proxy country (optional, default to us)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinGetAPublicPostCall(String postSlug, String country, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/linkedin/posts/{post_slug}"
            .replace("{" + "post_slug" + "}", localVarApiClient.escapeString(postSlug.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (country != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("country", country));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call linkedinGetAPublicPostValidateBeforeCall(String postSlug, String country, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'postSlug' is set
        if (postSlug == null) {
            throw new ApiException("Missing the required parameter 'postSlug' when calling linkedinGetAPublicPost(Async)");
        }

        return linkedinGetAPublicPostCall(postSlug, country, _callback);

    }

    /**
     * Get a public post
     * A public activity share — text, author, reactions, comments (JSON-LD).
     * @param postSlug  (required)
     * @param country Residential proxy country (optional, default to us)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object linkedinGetAPublicPost(String postSlug, String country) throws ApiException {
        ApiResponse<Object> localVarResp = linkedinGetAPublicPostWithHttpInfo(postSlug, country);
        return localVarResp.getData();
    }

    /**
     * Get a public post
     * A public activity share — text, author, reactions, comments (JSON-LD).
     * @param postSlug  (required)
     * @param country Residential proxy country (optional, default to us)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> linkedinGetAPublicPostWithHttpInfo(String postSlug, String country) throws ApiException {
        okhttp3.Call localVarCall = linkedinGetAPublicPostValidateBeforeCall(postSlug, country, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get a public post (asynchronously)
     * A public activity share — text, author, reactions, comments (JSON-LD).
     * @param postSlug  (required)
     * @param country Residential proxy country (optional, default to us)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinGetAPublicPostAsync(String postSlug, String country, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = linkedinGetAPublicPostValidateBeforeCall(postSlug, country, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for linkedinGetCompany
     * @param universalName  (required)
     * @param country Residential proxy country (optional, default to us)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinGetCompanyCall(String universalName, String country, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/linkedin/companies/{universal_name}"
            .replace("{" + "universal_name" + "}", localVarApiClient.escapeString(universalName.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (country != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("country", country));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call linkedinGetCompanyValidateBeforeCall(String universalName, String country, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'universalName' is set
        if (universalName == null) {
            throw new ApiException("Missing the required parameter 'universalName' when calling linkedinGetCompany(Async)");
        }

        return linkedinGetCompanyCall(universalName, country, _callback);

    }

    /**
     * Get company
     * Public company page — industry, size, HQ, followers, specialties (JSON-LD + SSR).
     * @param universalName  (required)
     * @param country Residential proxy country (optional, default to us)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object linkedinGetCompany(String universalName, String country) throws ApiException {
        ApiResponse<Object> localVarResp = linkedinGetCompanyWithHttpInfo(universalName, country);
        return localVarResp.getData();
    }

    /**
     * Get company
     * Public company page — industry, size, HQ, followers, specialties (JSON-LD + SSR).
     * @param universalName  (required)
     * @param country Residential proxy country (optional, default to us)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> linkedinGetCompanyWithHttpInfo(String universalName, String country) throws ApiException {
        okhttp3.Call localVarCall = linkedinGetCompanyValidateBeforeCall(universalName, country, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get company (asynchronously)
     * Public company page — industry, size, HQ, followers, specialties (JSON-LD + SSR).
     * @param universalName  (required)
     * @param country Residential proxy country (optional, default to us)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinGetCompanyAsync(String universalName, String country, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = linkedinGetCompanyValidateBeforeCall(universalName, country, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for linkedinGetJobDetail
     * @param jobId  (required)
     * @param country Residential proxy country (optional, default to us)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinGetJobDetailCall(String jobId, String country, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/linkedin/jobs/{job_id}"
            .replace("{" + "job_id" + "}", localVarApiClient.escapeString(jobId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (country != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("country", country));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call linkedinGetJobDetailValidateBeforeCall(String jobId, String country, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'jobId' is set
        if (jobId == null) {
            throw new ApiException("Missing the required parameter 'jobId' when calling linkedinGetJobDetail(Async)");
        }

        return linkedinGetJobDetailCall(jobId, country, _callback);

    }

    /**
     * Get job detail
     * Full detail for one job posting (guest API, no login).
     * @param jobId  (required)
     * @param country Residential proxy country (optional, default to us)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object linkedinGetJobDetail(String jobId, String country) throws ApiException {
        ApiResponse<Object> localVarResp = linkedinGetJobDetailWithHttpInfo(jobId, country);
        return localVarResp.getData();
    }

    /**
     * Get job detail
     * Full detail for one job posting (guest API, no login).
     * @param jobId  (required)
     * @param country Residential proxy country (optional, default to us)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> linkedinGetJobDetailWithHttpInfo(String jobId, String country) throws ApiException {
        okhttp3.Call localVarCall = linkedinGetJobDetailValidateBeforeCall(jobId, country, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get job detail (asynchronously)
     * Full detail for one job posting (guest API, no login).
     * @param jobId  (required)
     * @param country Residential proxy country (optional, default to us)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinGetJobDetailAsync(String jobId, String country, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = linkedinGetJobDetailValidateBeforeCall(jobId, country, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for linkedinGetPublicProfile
     * @param publicId  (required)
     * @param country Residential proxy country (optional, default to us)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinGetPublicProfileCall(String publicId, String country, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/linkedin/profiles/{public_id}"
            .replace("{" + "public_id" + "}", localVarApiClient.escapeString(publicId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (country != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("country", country));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call linkedinGetPublicProfileValidateBeforeCall(String publicId, String country, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'publicId' is set
        if (publicId == null) {
            throw new ApiException("Missing the required parameter 'publicId' when calling linkedinGetPublicProfile(Async)");
        }

        return linkedinGetPublicProfileCall(publicId, country, _callback);

    }

    /**
     * Get public profile
     * Public profile by vanity id (the &#x60;&#x60;/in/{public_id}&#x60;&#x60; slug) — name, headline, location, about, experience, education (public JSON-LD + SSR subset).
     * @param publicId  (required)
     * @param country Residential proxy country (optional, default to us)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object linkedinGetPublicProfile(String publicId, String country) throws ApiException {
        ApiResponse<Object> localVarResp = linkedinGetPublicProfileWithHttpInfo(publicId, country);
        return localVarResp.getData();
    }

    /**
     * Get public profile
     * Public profile by vanity id (the &#x60;&#x60;/in/{public_id}&#x60;&#x60; slug) — name, headline, location, about, experience, education (public JSON-LD + SSR subset).
     * @param publicId  (required)
     * @param country Residential proxy country (optional, default to us)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> linkedinGetPublicProfileWithHttpInfo(String publicId, String country) throws ApiException {
        okhttp3.Call localVarCall = linkedinGetPublicProfileValidateBeforeCall(publicId, country, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get public profile (asynchronously)
     * Public profile by vanity id (the &#x60;&#x60;/in/{public_id}&#x60;&#x60; slug) — name, headline, location, about, experience, education (public JSON-LD + SSR subset).
     * @param publicId  (required)
     * @param country Residential proxy country (optional, default to us)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinGetPublicProfileAsync(String publicId, String country, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = linkedinGetPublicProfileValidateBeforeCall(publicId, country, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for linkedinGetSchool
     * @param universalName  (required)
     * @param country Residential proxy country (optional, default to us)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinGetSchoolCall(String universalName, String country, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/linkedin/schools/{universal_name}"
            .replace("{" + "universal_name" + "}", localVarApiClient.escapeString(universalName.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (country != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("country", country));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call linkedinGetSchoolValidateBeforeCall(String universalName, String country, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'universalName' is set
        if (universalName == null) {
            throw new ApiException("Missing the required parameter 'universalName' when calling linkedinGetSchool(Async)");
        }

        return linkedinGetSchoolCall(universalName, country, _callback);

    }

    /**
     * Get school
     * Public school page — name, description, website, follower/alumni counts.
     * @param universalName  (required)
     * @param country Residential proxy country (optional, default to us)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object linkedinGetSchool(String universalName, String country) throws ApiException {
        ApiResponse<Object> localVarResp = linkedinGetSchoolWithHttpInfo(universalName, country);
        return localVarResp.getData();
    }

    /**
     * Get school
     * Public school page — name, description, website, follower/alumni counts.
     * @param universalName  (required)
     * @param country Residential proxy country (optional, default to us)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> linkedinGetSchoolWithHttpInfo(String universalName, String country) throws ApiException {
        okhttp3.Call localVarCall = linkedinGetSchoolValidateBeforeCall(universalName, country, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get school (asynchronously)
     * Public school page — name, description, website, follower/alumni counts.
     * @param universalName  (required)
     * @param country Residential proxy country (optional, default to us)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinGetSchoolAsync(String universalName, String country, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = linkedinGetSchoolValidateBeforeCall(universalName, country, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for linkedinLinkedinScraperHealthCheck
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinLinkedinScraperHealthCheckCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/linkedin/health";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call linkedinLinkedinScraperHealthCheckValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return linkedinLinkedinScraperHealthCheckCall(_callback);

    }

    /**
     * LinkedIn scraper health check
     * Check health of the LinkedIn scraper service (accepts HEAD).
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public Object linkedinLinkedinScraperHealthCheck() throws ApiException {
        ApiResponse<Object> localVarResp = linkedinLinkedinScraperHealthCheckWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * LinkedIn scraper health check
     * Check health of the LinkedIn scraper service (accepts HEAD).
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> linkedinLinkedinScraperHealthCheckWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = linkedinLinkedinScraperHealthCheckValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * LinkedIn scraper health check (asynchronously)
     * Check health of the LinkedIn scraper service (accepts HEAD).
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinLinkedinScraperHealthCheckAsync(final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = linkedinLinkedinScraperHealthCheckValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for linkedinLinkedinScraperHealthCheckHead
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinLinkedinScraperHealthCheckHeadCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/linkedin/health";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "HEAD", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call linkedinLinkedinScraperHealthCheckHeadValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return linkedinLinkedinScraperHealthCheckHeadCall(_callback);

    }

    /**
     * LinkedIn scraper health check
     * Check health of the LinkedIn scraper service (accepts HEAD).
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public Object linkedinLinkedinScraperHealthCheckHead() throws ApiException {
        ApiResponse<Object> localVarResp = linkedinLinkedinScraperHealthCheckHeadWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * LinkedIn scraper health check
     * Check health of the LinkedIn scraper service (accepts HEAD).
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> linkedinLinkedinScraperHealthCheckHeadWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = linkedinLinkedinScraperHealthCheckHeadValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * LinkedIn scraper health check (asynchronously)
     * Check health of the LinkedIn scraper service (accepts HEAD).
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinLinkedinScraperHealthCheckHeadAsync(final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = linkedinLinkedinScraperHealthCheckHeadValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for linkedinSearchLinkedinJobs
     * @param keywords Job title / keywords (optional)
     * @param location Location text, e.g. &#39;New York&#39; (optional)
     * @param geoId LinkedIn numeric geo id (overrides location) (optional)
     * @param companyId Restrict to a company (numeric id) (optional)
     * @param datePosted past_24h | past_week | past_month | any (optional)
     * @param experience internship|entry|associate|mid_senior|director|executive (comma-separated) (optional)
     * @param jobType full_time|part_time|contract|temporary|internship|volunteer|other (optional)
     * @param workplace onsite|remote|hybrid (comma-separated) (optional)
     * @param sort relevant | recent (optional)
     * @param start Pagination offset (0, 25, 50, ...) (optional, default to 0)
     * @param country Residential proxy country (optional, default to us)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinSearchLinkedinJobsCall(String keywords, String location, String geoId, String companyId, String datePosted, String experience, String jobType, String workplace, String sort, Integer start, String country, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/linkedin/jobs/search";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (keywords != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("keywords", keywords));
        }

        if (location != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("location", location));
        }

        if (geoId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("geo_id", geoId));
        }

        if (companyId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("company_id", companyId));
        }

        if (datePosted != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("date_posted", datePosted));
        }

        if (experience != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("experience", experience));
        }

        if (jobType != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("job_type", jobType));
        }

        if (workplace != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("workplace", workplace));
        }

        if (sort != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sort", sort));
        }

        if (start != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("start", start));
        }

        if (country != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("country", country));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call linkedinSearchLinkedinJobsValidateBeforeCall(String keywords, String location, String geoId, String companyId, String datePosted, String experience, String jobType, String workplace, String sort, Integer start, String country, final ApiCallback _callback) throws ApiException {
        return linkedinSearchLinkedinJobsCall(keywords, location, geoId, companyId, datePosted, experience, jobType, workplace, sort, start, country, _callback);

    }

    /**
     * Search LinkedIn jobs
     * Search public LinkedIn job postings (guest API, no login).
     * @param keywords Job title / keywords (optional)
     * @param location Location text, e.g. &#39;New York&#39; (optional)
     * @param geoId LinkedIn numeric geo id (overrides location) (optional)
     * @param companyId Restrict to a company (numeric id) (optional)
     * @param datePosted past_24h | past_week | past_month | any (optional)
     * @param experience internship|entry|associate|mid_senior|director|executive (comma-separated) (optional)
     * @param jobType full_time|part_time|contract|temporary|internship|volunteer|other (optional)
     * @param workplace onsite|remote|hybrid (comma-separated) (optional)
     * @param sort relevant | recent (optional)
     * @param start Pagination offset (0, 25, 50, ...) (optional, default to 0)
     * @param country Residential proxy country (optional, default to us)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object linkedinSearchLinkedinJobs(String keywords, String location, String geoId, String companyId, String datePosted, String experience, String jobType, String workplace, String sort, Integer start, String country) throws ApiException {
        ApiResponse<Object> localVarResp = linkedinSearchLinkedinJobsWithHttpInfo(keywords, location, geoId, companyId, datePosted, experience, jobType, workplace, sort, start, country);
        return localVarResp.getData();
    }

    /**
     * Search LinkedIn jobs
     * Search public LinkedIn job postings (guest API, no login).
     * @param keywords Job title / keywords (optional)
     * @param location Location text, e.g. &#39;New York&#39; (optional)
     * @param geoId LinkedIn numeric geo id (overrides location) (optional)
     * @param companyId Restrict to a company (numeric id) (optional)
     * @param datePosted past_24h | past_week | past_month | any (optional)
     * @param experience internship|entry|associate|mid_senior|director|executive (comma-separated) (optional)
     * @param jobType full_time|part_time|contract|temporary|internship|volunteer|other (optional)
     * @param workplace onsite|remote|hybrid (comma-separated) (optional)
     * @param sort relevant | recent (optional)
     * @param start Pagination offset (0, 25, 50, ...) (optional, default to 0)
     * @param country Residential proxy country (optional, default to us)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> linkedinSearchLinkedinJobsWithHttpInfo(String keywords, String location, String geoId, String companyId, String datePosted, String experience, String jobType, String workplace, String sort, Integer start, String country) throws ApiException {
        okhttp3.Call localVarCall = linkedinSearchLinkedinJobsValidateBeforeCall(keywords, location, geoId, companyId, datePosted, experience, jobType, workplace, sort, start, country, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Search LinkedIn jobs (asynchronously)
     * Search public LinkedIn job postings (guest API, no login).
     * @param keywords Job title / keywords (optional)
     * @param location Location text, e.g. &#39;New York&#39; (optional)
     * @param geoId LinkedIn numeric geo id (overrides location) (optional)
     * @param companyId Restrict to a company (numeric id) (optional)
     * @param datePosted past_24h | past_week | past_month | any (optional)
     * @param experience internship|entry|associate|mid_senior|director|executive (comma-separated) (optional)
     * @param jobType full_time|part_time|contract|temporary|internship|volunteer|other (optional)
     * @param workplace onsite|remote|hybrid (comma-separated) (optional)
     * @param sort relevant | recent (optional)
     * @param start Pagination offset (0, 25, 50, ...) (optional, default to 0)
     * @param country Residential proxy country (optional, default to us)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinSearchLinkedinJobsAsync(String keywords, String location, String geoId, String companyId, String datePosted, String experience, String jobType, String workplace, String sort, Integer start, String country, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = linkedinSearchLinkedinJobsValidateBeforeCall(keywords, location, geoId, companyId, datePosted, experience, jobType, workplace, sort, start, country, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for linkedinSuggestLocationGeoIds
     * @param query Location text, e.g. &#39;London&#39; (required)
     * @param type geo | company (optional, default to geo)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinSuggestLocationGeoIdsCall(String query, String type, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/linkedin/geo/suggest";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (query != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("query", query));
        }

        if (type != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("type", type));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call linkedinSuggestLocationGeoIdsValidateBeforeCall(String query, String type, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'query' is set
        if (query == null) {
            throw new ApiException("Missing the required parameter 'query' when calling linkedinSuggestLocationGeoIds(Async)");
        }

        return linkedinSuggestLocationGeoIdsCall(query, type, _callback);

    }

    /**
     * Suggest location geo ids
     * Resolve a name to LinkedIn ids (job-search &#x60;&#x60;geo_id&#x60;&#x60; / &#x60;&#x60;company_id&#x60;&#x60; helper).
     * @param query Location text, e.g. &#39;London&#39; (required)
     * @param type geo | company (optional, default to geo)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public Object linkedinSuggestLocationGeoIds(String query, String type) throws ApiException {
        ApiResponse<Object> localVarResp = linkedinSuggestLocationGeoIdsWithHttpInfo(query, type);
        return localVarResp.getData();
    }

    /**
     * Suggest location geo ids
     * Resolve a name to LinkedIn ids (job-search &#x60;&#x60;geo_id&#x60;&#x60; / &#x60;&#x60;company_id&#x60;&#x60; helper).
     * @param query Location text, e.g. &#39;London&#39; (required)
     * @param type geo | company (optional, default to geo)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> linkedinSuggestLocationGeoIdsWithHttpInfo(String query, String type) throws ApiException {
        okhttp3.Call localVarCall = linkedinSuggestLocationGeoIdsValidateBeforeCall(query, type, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Suggest location geo ids (asynchronously)
     * Resolve a name to LinkedIn ids (job-search &#x60;&#x60;geo_id&#x60;&#x60; / &#x60;&#x60;company_id&#x60;&#x60; helper).
     * @param query Location text, e.g. &#39;London&#39; (required)
     * @param type geo | company (optional, default to geo)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Validation Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call linkedinSuggestLocationGeoIdsAsync(String query, String type, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = linkedinSuggestLocationGeoIdsValidateBeforeCall(query, type, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
