/*
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.scrapebadger.client.api;

import com.scrapebadger.client.ApiException;
import com.scrapebadger.client.model.HTTPValidationError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BaiduApi
 */
@Disabled
public class BaiduApiTest {

    private final BaiduApi api = new BaiduApi();

    /**
     * Baidu image search
     *
     * Baidu image search via the acjson JSON API.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void baiduBaiduImageSearchTest() throws ApiException {
        String query = null;
        Integer page = null;
        Object response = api.baiduBaiduImageSearch(query, page);
        // TODO: test validations
    }

    /**
     * Baidu news search
     *
     * Baidu news vertical — articles with source, publish date and real URLs.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void baiduBaiduNewsSearchTest() throws ApiException {
        String query = null;
        Integer page = null;
        Object response = api.baiduBaiduNewsSearch(query, page);
        // TODO: test validations
    }

    /**
     * Baidu scraper health check
     *
     * Check health of the Baidu scraper service (accepts HEAD for UptimeRobot).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void baiduBaiduScraperHealthCheckTest() throws ApiException {
        Object response = api.baiduBaiduScraperHealthCheck();
        // TODO: test validations
    }

    /**
     * Baidu scraper health check
     *
     * Check health of the Baidu scraper service (accepts HEAD for UptimeRobot).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void baiduBaiduScraperHealthCheckHeadTest() throws ApiException {
        Object response = api.baiduBaiduScraperHealthCheckHead();
        // TODO: test validations
    }

    /**
     * Baidu web search
     *
     * Baidu web SERP — organic results with real target URLs, related searches, total count.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void baiduBaiduWebSearchTest() throws ApiException {
        String query = null;
        Integer page = null;
        Integer num = null;
        Object response = api.baiduBaiduWebSearch(query, page, num);
        // TODO: test validations
    }

    /**
     * Search suggestions
     *
     * Baidu search-box suggestions.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void baiduSearchSuggestionsTest() throws ApiException {
        String query = null;
        Object response = api.baiduSearchSuggestions(query);
        // TODO: test validations
    }

}
