/*
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.scrapebadger.client.api;

import com.scrapebadger.client.ApiException;
import com.scrapebadger.client.model.HTTPValidationError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BookingApi
 */
@Disabled
public class BookingApiTest {

    private final BookingApi api = new BookingApi();

    /**
     * Booking scraper health check
     *
     * Check health of the Booking scraper service (accepts HEAD).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void bookingBookingScraperHealthCheckTest() throws ApiException {
        Object response = api.bookingBookingScraperHealthCheck();
        // TODO: test validations
    }

    /**
     * Booking scraper health check
     *
     * Check health of the Booking scraper service (accepts HEAD).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void bookingBookingScraperHealthCheckHeadTest() throws ApiException {
        Object response = api.bookingBookingScraperHealthCheckHead();
        // TODO: test validations
    }

    /**
     * Get property detail
     *
     * Full detail for one property: description, address and coordinates, star rating, review score with per-category breakdown, facilities, house rules, room types with occupancy and beds, photos and guest Q&amp;A.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void bookingGetPropertyDetailTest() throws ApiException {
        String countryCode = null;
        String slug = null;
        Integer photos = null;
        Integer questions = null;
        String language = null;
        Object response = api.bookingGetPropertyDetail(countryCode, slug, photos, questions, language);
        // TODO: test validations
    }

    /**
     * Get property reviews
     *
     * Paginated guest reviews with score, positive and negative text, stay dates, room type, guest country and type, photos and the partner&#39;s reply.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void bookingGetPropertyReviewsTest() throws ApiException {
        String countryCode = null;
        String slug = null;
        Integer limit = null;
        Integer offset = null;
        String sort = null;
        String reviewLanguage = null;
        String guestType = null;
        String language = null;
        Object response = api.bookingGetPropertyReviews(countryCode, slug, limit, offset, sort, reviewLanguage, guestType, language);
        // TODO: test validations
    }

    /**
     * Get room types and live rates
     *
     * Every room type at one property with every rate bookable on it for the given dates — price, price before discount, price per night, discounts and badges — plus per-room facilities, bed layouts, occupancy and photos. /search returns only the cheapest rate per property; this returns the whole table.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void bookingGetRoomTypesAndLiveRatesTest() throws ApiException {
        String countryCode = null;
        String slug = null;
        String checkin = null;
        String checkout = null;
        Integer adults = null;
        String children = null;
        Integer rooms = null;
        String currency = null;
        String language = null;
        Object response = api.bookingGetRoomTypesAndLiveRates(countryCode, slug, checkin, checkout, adults, children, rooms, currency, language);
        // TODO: test validations
    }

    /**
     * Search destinations
     *
     * Resolve a place name to Booking&#39;s &#x60;dest_id&#x60;/&#x60;dest_type&#x60;, with coordinates and country — feed the pair back into /search for an exact match.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void bookingSearchDestinationsTest() throws ApiException {
        String query = null;
        Integer limit = null;
        String language = null;
        Object response = api.bookingSearchDestinations(query, limit, language);
        // TODO: test validations
    }

    /**
     * Search properties
     *
     * Search Booking.com properties by destination, with dates, occupancy, sorting and filters. Returns prices, review scores, coordinates, room configuration and photos. Paginate with &#x60;offset&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void bookingSearchPropertiesTest() throws ApiException {
        String location = null;
        Integer destId = null;
        String destType = null;
        String checkin = null;
        String checkout = null;
        Integer adults = null;
        String children = null;
        Integer rooms = null;
        Integer offset = null;
        Integer limit = null;
        String sort = null;
        String filters = null;
        String currency = null;
        String language = null;
        Object response = api.bookingSearchProperties(location, destId, destType, checkin, checkout, adults, children, rooms, offset, limit, sort, filters, currency, language);
        // TODO: test validations
    }

}
