/*
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.scrapebadger.client.api;

import com.scrapebadger.client.ApiException;
import com.scrapebadger.client.model.HTTPValidationError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FacebookApi
 */
@Disabled
public class FacebookApiTest {

    private final FacebookApi api = new FacebookApi();

    /**
     * Browse a Marketplace category
     *
     * Browse Marketplace listings in a category (vehicles, electronics, ...).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookBrowseAMarketplaceCategoryTest() throws ApiException {
        String category = null;
        String location = null;
        Integer minPrice = null;
        Integer maxPrice = null;
        String sortBy = null;
        String after = null;
        Object response = api.facebookBrowseAMarketplaceCategory(category, location, minPrice, maxPrice, sortBy, after);
        // TODO: test validations
    }

    /**
     * Get a Marketplace item
     *
     * Get full detail for a single Marketplace listing.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookGetAMarketplaceItemTest() throws ApiException {
        String itemId = null;
        Object response = api.facebookGetAMarketplaceItem(itemId);
        // TODO: test validations
    }

    /**
     * Get advertiser page info
     *
     * Get advertiser page info: category, followers, page transparency (creation date, name history, managing organization, admin-account locations), related pages, and ad spend (for political/issue advertisers).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookGetAdvertiserPageInfoTest() throws ApiException {
        String pageId = null;
        String country = null;
        Object response = api.facebookGetAdvertiserPageInfo(pageId, country);
        // TODO: test validations
    }

    /**
     * Get an ad
     *
     * Get a single Ad Library ad by its archive id. For EU/UK-targeted ads the response also includes transparency insights (payer/beneficiary, total EU reach, and age/gender/country reach breakdowns).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookGetAnAdTest() throws ApiException {
        String adArchiveId = null;
        String country = null;
        Object response = api.facebookGetAnAd(adArchiveId, country);
        // TODO: test validations
    }

    /**
     * Get group detail
     *
     * Get a Facebook group&#39;s details.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookGetGroupDetailTest() throws ApiException {
        String groupId = null;
        Object response = api.facebookGetGroupDetail(groupId);
        // TODO: test validations
    }

    /**
     * Get group posts
     *
     * Get a Facebook group&#39;s post feed.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookGetGroupPostsTest() throws ApiException {
        String groupId = null;
        String after = null;
        Object response = api.facebookGetGroupPosts(groupId, after);
        // TODO: test validations
    }

    /**
     * Get page detail
     *
     * Get a Facebook Page&#39;s profile (name, category, followers, about).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookGetPageDetailTest() throws ApiException {
        String identifier = null;
        Object response = api.facebookGetPageDetail(identifier);
        // TODO: test validations
    }

    /**
     * Get page posts
     *
     * Get a Facebook Page&#39;s timeline posts.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookGetPagePostsTest() throws ApiException {
        String identifier = null;
        String after = null;
        Object response = api.facebookGetPagePosts(identifier, after);
        // TODO: test validations
    }

    /**
     * Get post comments
     *
     * Get a Facebook post&#39;s comment thread (paginated).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookGetPostCommentsTest() throws ApiException {
        String postId = null;
        String after = null;
        String sort = null;
        Object response = api.facebookGetPostComments(postId, after, sort);
        // TODO: test validations
    }

    /**
     * Get post detail
     *
     * Get a Facebook post&#39;s detail plus its top comments.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookGetPostDetailTest() throws ApiException {
        String postId = null;
        Object response = api.facebookGetPostDetail(postId);
        // TODO: test validations
    }

    /**
     * Get profile detail
     *
     * Get a Facebook profile&#39;s details.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookGetProfileDetailTest() throws ApiException {
        String identifier = null;
        Object response = api.facebookGetProfileDetail(identifier);
        // TODO: test validations
    }

    /**
     * Get profile posts
     *
     * Get a Facebook profile&#39;s timeline posts.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookGetProfilePostsTest() throws ApiException {
        String identifier = null;
        String after = null;
        Object response = api.facebookGetProfilePosts(identifier, after);
        // TODO: test validations
    }

    /**
     * List categories
     *
     * List Marketplace category slugs (free).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookListCategoriesTest() throws ApiException {
        Object response = api.facebookListCategories();
        // TODO: test validations
    }

    /**
     * List locations
     *
     * List common Marketplace location slugs (free).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookListLocationsTest() throws ApiException {
        Object response = api.facebookListLocations();
        // TODO: test validations
    }

    /**
     * Search advertiser pages
     *
     * Search advertiser Pages in the Ad Library — returns page ids, categories, likes/followers, verification and Instagram handles.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookSearchAdvertiserPagesTest() throws ApiException {
        String query = null;
        String country = null;
        Object response = api.facebookSearchAdvertiserPages(query, country);
        // TODO: test validations
    }

    /**
     * Search events
     *
     * Search Facebook events.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookSearchEventsTest() throws ApiException {
        String q = null;
        String after = null;
        Object response = api.facebookSearchEvents(q, after);
        // TODO: test validations
    }

    /**
     * Search everything
     *
     * Global Facebook search (top results across pages, people, groups, posts).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookSearchEverythingTest() throws ApiException {
        String q = null;
        String after = null;
        Object response = api.facebookSearchEverything(q, after);
        // TODO: test validations
    }

    /**
     * Search groups
     *
     * Search Facebook groups.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookSearchGroupsTest() throws ApiException {
        String q = null;
        String after = null;
        Object response = api.facebookSearchGroups(q, after);
        // TODO: test validations
    }

    /**
     * Search Marketplace
     *
     * Search Facebook Marketplace listings by keyword and location.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookSearchMarketplaceTest() throws ApiException {
        String query = null;
        String location = null;
        Integer minPrice = null;
        Integer maxPrice = null;
        Integer daysSinceListed = null;
        String sortBy = null;
        String itemCondition = null;
        String deliveryMethod = null;
        String after = null;
        Object response = api.facebookSearchMarketplace(query, location, minPrice, maxPrice, daysSinceListed, sortBy, itemCondition, deliveryMethod, after);
        // TODO: test validations
    }

    /**
     * Search Pages
     *
     * Search Facebook Pages.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookSearchPagesTest() throws ApiException {
        String q = null;
        String after = null;
        Object response = api.facebookSearchPages(q, after);
        // TODO: test validations
    }

    /**
     * Search people
     *
     * Search Facebook profiles.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookSearchPeopleTest() throws ApiException {
        String q = null;
        String after = null;
        Object response = api.facebookSearchPeople(q, after);
        // TODO: test validations
    }

    /**
     * Search places
     *
     * Search Facebook places.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookSearchPlacesTest() throws ApiException {
        String q = null;
        String after = null;
        Object response = api.facebookSearchPlaces(q, after);
        // TODO: test validations
    }

    /**
     * Search posts
     *
     * Search public Facebook posts.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookSearchPostsTest() throws ApiException {
        String q = null;
        String after = null;
        Object response = api.facebookSearchPosts(q, after);
        // TODO: test validations
    }

    /**
     * Search the Ad Library
     *
     * Search the Facebook Ad Library.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void facebookSearchTheAdLibraryTest() throws ApiException {
        String query = null;
        String country = null;
        String adType = null;
        String activeStatus = null;
        String after = null;
        Object response = api.facebookSearchTheAdLibrary(query, country, adType, activeStatus, after);
        // TODO: test validations
    }

}
