/*
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.scrapebadger.client.api;

import com.scrapebadger.client.ApiException;
import com.scrapebadger.client.model.HTTPValidationError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GooglePlayApi
 */
@Disabled
public class GooglePlayApiTest {

    private final GooglePlayApi api = new GooglePlayApi();

    /**
     * Browse a category
     *
     * The top apps within a Play category.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void googlePlayBrowseACategoryTest() throws ApiException {
        String categoryId = null;
        String country = null;
        String lang = null;
        Integer num = null;
        Object response = api.googlePlayBrowseACategory(categoryId, country, lang, num);
        // TODO: test validations
    }

    /**
     * Get app detail
     *
     * Full app detail: ratings histogram, installs, pricing, IAP, developer, screenshots, version metadata and what&#39;s-new.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void googlePlayGetAppDetailTest() throws ApiException {
        String appId = null;
        String country = null;
        String lang = null;
        Object response = api.googlePlayGetAppDetail(appId, country, lang);
        // TODO: test validations
    }

    /**
     * Get app permissions
     *
     * The app&#39;s requested Android permissions, grouped.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void googlePlayGetAppPermissionsTest() throws ApiException {
        String appId = null;
        String lang = null;
        Object response = api.googlePlayGetAppPermissions(appId, lang);
        // TODO: test validations
    }

    /**
     * Get app reviews
     *
     * Paginated app reviews via the Play batchexecute RPC.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void googlePlayGetAppReviewsTest() throws ApiException {
        String appId = null;
        String country = null;
        String lang = null;
        String sort = null;
        Integer count = null;
        String pageToken = null;
        Object response = api.googlePlayGetAppReviews(appId, country, lang, sort, count, pageToken);
        // TODO: test validations
    }

    /**
     * Get developer apps
     *
     * A developer&#39;s published apps.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void googlePlayGetDeveloperAppsTest() throws ApiException {
        String developer = null;
        String country = null;
        String lang = null;
        Integer num = null;
        Object response = api.googlePlayGetDeveloperApps(developer, country, lang, num);
        // TODO: test validations
    }

    /**
     * Get similar apps
     *
     * Apps Google Play lists as similar to this one.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void googlePlayGetSimilarAppsTest() throws ApiException {
        String appId = null;
        String country = null;
        String lang = null;
        Object response = api.googlePlayGetSimilarApps(appId, country, lang);
        // TODO: test validations
    }

    /**
     * List categories
     *
     * The Google Play app/game category ids.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void googlePlayListCategoriesTest() throws ApiException {
        Object response = api.googlePlayListCategories();
        // TODO: test validations
    }

    /**
     * List markets
     *
     * Supported Google Play store countries and languages.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void googlePlayListMarketsTest() throws ApiException {
        Object response = api.googlePlayListMarkets();
        // TODO: test validations
    }

    /**
     * Search apps
     *
     * Search Google Play for apps and games (the ~30 server-rendered results; Play exposes no page parameter).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void googlePlaySearchAppsTest() throws ApiException {
        String query = null;
        String country = null;
        String lang = null;
        String price = null;
        Object response = api.googlePlaySearchApps(query, country, lang, price);
        // TODO: test validations
    }

    /**
     * Top charts
     *
     * Top charts for a collection, optionally scoped to a category.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void googlePlayTopChartsTest() throws ApiException {
        String collection = null;
        String category = null;
        String country = null;
        String lang = null;
        Object response = api.googlePlayTopCharts(collection, category, country, lang);
        // TODO: test validations
    }

}
