/*
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.scrapebadger.client.api;

import com.scrapebadger.client.ApiException;
import com.scrapebadger.client.model.HTTPValidationError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InstagramApi
 */
@Disabled
public class InstagramApiTest {

    private final InstagramApi api = new InstagramApi();

    /**
     * About this account
     *
     * Country, join date and former usernames.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramAboutThisAccountTest() throws ApiException {
        String username = null;
        Object response = api.instagramAboutThisAccount(username);
        // TODO: test validations
    }

    /**
     * Blended top search
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramBlendedTopSearchTest() throws ApiException {
        String query = null;
        Object response = api.instagramBlendedTopSearch(query);
        // TODO: test validations
    }

    /**
     * Get active stories
     *
     * Active stories (account pool only).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramGetActiveStoriesTest() throws ApiException {
        String username = null;
        Object response = api.instagramGetActiveStories(username);
        // TODO: test validations
    }

    /**
     * Get audio track
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramGetAudioTrackTest() throws ApiException {
        String audioId = null;
        Object response = api.instagramGetAudioTrack(audioId);
        // TODO: test validations
    }

    /**
     * Get comments
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramGetCommentsTest() throws ApiException {
        String code = null;
        Integer amount = null;
        String cursor = null;
        Object response = api.instagramGetComments(code, amount, cursor);
        // TODO: test validations
    }

    /**
     * Get followers
     *
     * Followers list, paginated (account pool).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramGetFollowersTest() throws ApiException {
        String username = null;
        Integer amount = null;
        String cursor = null;
        String order = null;
        Object response = api.instagramGetFollowers(username, amount, cursor, order);
        // TODO: test validations
    }

    /**
     * Get following
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramGetFollowingTest() throws ApiException {
        String username = null;
        Integer amount = null;
        String cursor = null;
        Object response = api.instagramGetFollowing(username, amount, cursor);
        // TODO: test validations
    }

    /**
     * Get hashtag info
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramGetHashtagInfoTest() throws ApiException {
        String tag = null;
        Object response = api.instagramGetHashtagInfo(tag);
        // TODO: test validations
    }

    /**
     * Get highlights
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramGetHighlightsTest() throws ApiException {
        String username = null;
        Object response = api.instagramGetHighlights(username);
        // TODO: test validations
    }

    /**
     * Get likers
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramGetLikersTest() throws ApiException {
        String code = null;
        Object response = api.instagramGetLikers(code);
        // TODO: test validations
    }

    /**
     * Get location
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramGetLocationTest() throws ApiException {
        Integer locationPk = null;
        Object response = api.instagramGetLocation(locationPk);
        // TODO: test validations
    }

    /**
     * Get post/reel detail
     *
     * Single post or reel: caption, media, counts, tags, location, carousel.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramGetPostReelDetailTest() throws ApiException {
        String code = null;
        Object response = api.instagramGetPostReelDetail(code);
        // TODO: test validations
    }

    /**
     * Get profile
     *
     * Full public profile: bio, counts, verification, business contact, links.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramGetProfileTest() throws ApiException {
        String username = null;
        Object response = api.instagramGetProfile(username);
        // TODO: test validations
    }

    /**
     * Get tagged posts
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramGetTaggedPostsTest() throws ApiException {
        String username = null;
        Integer amount = null;
        String cursor = null;
        Object response = api.instagramGetTaggedPosts(username, amount, cursor);
        // TODO: test validations
    }

    /**
     * Get user posts
     *
     * Timeline posts, paginated.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramGetUserPostsTest() throws ApiException {
        String username = null;
        Integer amount = null;
        String cursor = null;
        Object response = api.instagramGetUserPosts(username, amount, cursor);
        // TODO: test validations
    }

    /**
     * Get user reels
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramGetUserReelsTest() throws ApiException {
        String username = null;
        Integer amount = null;
        String cursor = null;
        Object response = api.instagramGetUserReels(username, amount, cursor);
        // TODO: test validations
    }

    /**
     * Health
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramHealthTest() throws ApiException {
        Object response = api.instagramHealth();
        // TODO: test validations
    }

    /**
     * Health
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramHealthHeadTest() throws ApiException {
        Object response = api.instagramHealthHead();
        // TODO: test validations
    }

    /**
     * Recent hashtag posts
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramRecentHashtagPostsTest() throws ApiException {
        String tag = null;
        Integer amount = null;
        String cursor = null;
        Object response = api.instagramRecentHashtagPosts(tag, amount, cursor);
        // TODO: test validations
    }

    /**
     * Related profiles
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramRelatedProfilesTest() throws ApiException {
        String username = null;
        Object response = api.instagramRelatedProfiles(username);
        // TODO: test validations
    }

    /**
     * Search hashtags
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramSearchHashtagsTest() throws ApiException {
        String query = null;
        Object response = api.instagramSearchHashtags(query);
        // TODO: test validations
    }

    /**
     * Search users
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramSearchUsersTest() throws ApiException {
        String query = null;
        Object response = api.instagramSearchUsers(query);
        // TODO: test validations
    }

    /**
     * Top hashtag posts
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void instagramTopHashtagPostsTest() throws ApiException {
        String tag = null;
        Integer amount = null;
        String cursor = null;
        Object response = api.instagramTopHashtagPosts(tag, amount, cursor);
        // TODO: test validations
    }

}
