/*
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.scrapebadger.client.api;

import com.scrapebadger.client.ApiException;
import com.scrapebadger.client.model.HTTPValidationError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NaverApi
 */
@Disabled
public class NaverApiTest {

    private final NaverApi api = new NaverApi();

    /**
     * Naver blog search
     *
     * Naver blog vertical — post title, blog name and real post URLs.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void naverNaverBlogSearchTest() throws ApiException {
        String query = null;
        Integer page = null;
        Object response = api.naverNaverBlogSearch(query, page);
        // TODO: test validations
    }

    /**
     * Naver DataLab shopping keyword insight
     *
     * DataLab Shopping Insight — top search keywords in a category over a window.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void naverNaverDatalabShoppingKeywordInsightTest() throws ApiException {
        String categoryId = null;
        String startDate = null;
        String endDate = null;
        String timeUnit = null;
        Integer count = null;
        Object response = api.naverNaverDatalabShoppingKeywordInsight(categoryId, startDate, endDate, timeUnit, count);
        // TODO: test validations
    }

    /**
     * Naver news search
     *
     * Naver news vertical — publisher, age string and real article URLs.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void naverNaverNewsSearchTest() throws ApiException {
        String query = null;
        Integer page = null;
        Object response = api.naverNaverNewsSearch(query, page);
        // TODO: test validations
    }

    /**
     * Naver place detail
     *
     * Naver Place detail by place id.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void naverNaverPlaceDetailTest() throws ApiException {
        String placeId = null;
        Object response = api.naverNaverPlaceDetail(placeId);
        // TODO: test validations
    }

    /**
     * Naver Place/Local search
     *
     * Naver Place/Local search — name, category, rating, hours status.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void naverNaverPlaceLocalSearchTest() throws ApiException {
        String query = null;
        Object response = api.naverNaverPlaceLocalSearch(query);
        // TODO: test validations
    }

    /**
     * Naver place visitor reviews
     *
     * Visitor reviews for a Naver place — rating, body, reviewer, voted keywords, photos.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void naverNaverPlaceVisitorReviewsTest() throws ApiException {
        String placeId = null;
        Object response = api.naverNaverPlaceVisitorReviews(placeId);
        // TODO: test validations
    }

    /**
     * Naver scraper health check
     *
     * Check health of the Naver scraper service (accepts HEAD for UptimeRobot).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void naverNaverScraperHealthCheckTest() throws ApiException {
        Object response = api.naverNaverScraperHealthCheck();
        // TODO: test validations
    }

    /**
     * Naver scraper health check
     *
     * Check health of the Naver scraper service (accepts HEAD for UptimeRobot).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void naverNaverScraperHealthCheckHeadTest() throws ApiException {
        Object response = api.naverNaverScraperHealthCheckHead();
        // TODO: test validations
    }

    /**
     * Naver Shopping bestseller rankings
     *
     * Naver Shopping bestseller rankings — ranked products with price, review score, mall.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void naverNaverShoppingBestsellerRankingsTest() throws ApiException {
        String categoryId = null;
        String ageType = null;
        String sortType = null;
        String periodType = null;
        Object response = api.naverNaverShoppingBestsellerRankings(categoryId, ageType, sortType, periodType);
        // TODO: test validations
    }

    /**
     * Naver Shopping category reference
     *
     * Naver Shopping top-level category ids (for bestsellers/keywords/insight). Free.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void naverNaverShoppingCategoryReferenceTest() throws ApiException {
        Object response = api.naverNaverShoppingCategoryReference();
        // TODO: test validations
    }

    /**
     * Naver Shopping trending keyword rankings
     *
     * Trending Naver Shopping keywords for a category (snxbest keyword rankings).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void naverNaverShoppingTrendingKeywordRankingsTest() throws ApiException {
        String categoryId = null;
        String ageType = null;
        String sortType = null;
        String periodType = null;
        Object response = api.naverNaverShoppingTrendingKeywordRankings(categoryId, ageType, sortType, periodType);
        // TODO: test validations
    }

    /**
     * Naver web search
     *
     * Naver integrated SERP — organic results plus the inline Place pack.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void naverNaverWebSearchTest() throws ApiException {
        String query = null;
        Integer page = null;
        Object response = api.naverNaverWebSearch(query, page);
        // TODO: test validations
    }

    /**
     * Search suggestions
     *
     * Naver search-box suggestions.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void naverSearchSuggestionsTest() throws ApiException {
        String query = null;
        Object response = api.naverSearchSuggestions(query);
        // TODO: test validations
    }

}
