/*
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.scrapebadger.client.api;

import com.scrapebadger.client.ApiException;
import com.scrapebadger.client.model.HTTPValidationError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TikTokApi
 */
@Disabled
public class TikTokApiTest {

    private final TikTokApi api = new TikTokApi();

    /**
     * General search
     *
     * General TikTok search — video results from the Top feed.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokGeneralSearchTest() throws ApiException {
        String query = null;
        String region = null;
        Integer count = null;
        String cursor = null;
        Object response = api.tiktokGeneralSearch(query, region, count, cursor);
        // TODO: test validations
    }

    /**
     * Get comment replies
     *
     * Get replies to a TikTok comment (best-effort).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokGetCommentRepliesTest() throws ApiException {
        String commentId = null;
        String videoId = null;
        String region = null;
        Integer count = null;
        String cursor = null;
        Object response = api.tiktokGetCommentReplies(commentId, videoId, region, count, cursor);
        // TODO: test validations
    }

    /**
     * Get comments
     *
     * Get top-level comments on a TikTok video.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokGetCommentsTest() throws ApiException {
        String videoId = null;
        String region = null;
        Integer count = null;
        String cursor = null;
        Object response = api.tiktokGetComments(videoId, region, count, cursor);
        // TODO: test validations
    }

    /**
     * Get followers (deprecated)
     *
     * DEPRECATED — TikTok followers require an authenticated account session. Returns HTTP 410.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokGetFollowersDeprecatedTest() throws ApiException {
        String username = null;
        String region = null;
        Integer count = null;
        Object response = api.tiktokGetFollowersDeprecated(username, region, count);
        // TODO: test validations
    }

    /**
     * Get following (deprecated)
     *
     * DEPRECATED — TikTok following requires an authenticated account session. Returns HTTP 410.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokGetFollowingDeprecatedTest() throws ApiException {
        String username = null;
        String region = null;
        Integer count = null;
        Object response = api.tiktokGetFollowingDeprecated(username, region, count);
        // TODO: test validations
    }

    /**
     * Get hashtag detail
     *
     * Get TikTok hashtag/challenge detail.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokGetHashtagDetailTest() throws ApiException {
        String name = null;
        String region = null;
        Object response = api.tiktokGetHashtagDetail(name, region);
        // TODO: test validations
    }

    /**
     * Get hashtag videos
     *
     * Get videos tagged with a TikTok hashtag.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokGetHashtagVideosTest() throws ApiException {
        String name = null;
        String region = null;
        Integer count = null;
        String cursor = null;
        Object response = api.tiktokGetHashtagVideos(name, region, count, cursor);
        // TODO: test validations
    }

    /**
     * Get liked videos (deprecated)
     *
     * DEPRECATED — TikTok liked videos require an authenticated account session. Returns HTTP 410.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokGetLikedVideosDeprecatedTest() throws ApiException {
        String username = null;
        String region = null;
        Integer count = null;
        Object response = api.tiktokGetLikedVideosDeprecated(username, region, count);
        // TODO: test validations
    }

    /**
     * Get music/sound detail
     *
     * Get TikTok sound/music detail.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokGetMusicSoundDetailTest() throws ApiException {
        String musicId = null;
        String region = null;
        Object response = api.tiktokGetMusicSoundDetail(musicId, region);
        // TODO: test validations
    }

    /**
     * Get music videos
     *
     * Get videos using a given TikTok sound.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokGetMusicVideosTest() throws ApiException {
        String musicId = null;
        String region = null;
        Integer count = null;
        String cursor = null;
        Object response = api.tiktokGetMusicVideos(musicId, region, count, cursor);
        // TODO: test validations
    }

    /**
     * Get oEmbed metadata
     *
     * Get cheap unauthenticated oEmbed metadata for a TikTok URL.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokGetOembedMetadataTest() throws ApiException {
        String url = null;
        String region = null;
        Object response = api.tiktokGetOembedMetadata(url, region);
        // TODO: test validations
    }

    /**
     * Get related videos
     *
     * Get TikTok&#39;s related videos for a given video.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokGetRelatedVideosTest() throws ApiException {
        String videoId = null;
        String region = null;
        Integer count = null;
        Object response = api.tiktokGetRelatedVideos(videoId, region, count);
        // TODO: test validations
    }

    /**
     * Get reposts
     *
     * Get videos a TikTok user has reposted.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokGetRepostsTest() throws ApiException {
        String username = null;
        String region = null;
        Integer count = null;
        Object response = api.tiktokGetReposts(username, region, count);
        // TODO: test validations
    }

    /**
     * Get TikTok ad detail
     *
     * Get a single ad&#39;s advertiser, creatives, and targeting/impression breakdown.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokGetTiktokAdDetailTest() throws ApiException {
        String adId = null;
        String region = null;
        Object response = api.tiktokGetTiktokAdDetail(adId, region);
        // TODO: test validations
    }

    /**
     * Get transcript
     *
     * Get subtitle/caption tracks for a TikTok video.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokGetTranscriptTest() throws ApiException {
        String videoId = null;
        String region = null;
        Object response = api.tiktokGetTranscript(videoId, region);
        // TODO: test validations
    }

    /**
     * Get user profile
     *
     * Get a TikTok user&#39;s full profile.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokGetUserProfileTest() throws ApiException {
        String username = null;
        String region = null;
        Object response = api.tiktokGetUserProfile(username, region);
        // TODO: test validations
    }

    /**
     * Get user videos
     *
     * Get a TikTok user&#39;s posted videos.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokGetUserVideosTest() throws ApiException {
        String username = null;
        String region = null;
        Integer count = null;
        String cursor = null;
        Object response = api.tiktokGetUserVideos(username, region, count, cursor);
        // TODO: test validations
    }

    /**
     * Get video detail
     *
     * Get full metadata for a single TikTok video/post.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokGetVideoDetailTest() throws ApiException {
        String videoId = null;
        String region = null;
        String username = null;
        Object response = api.tiktokGetVideoDetail(videoId, region, username);
        // TODO: test validations
    }

    /**
     * Health check
     *
     * Check health of the TikTok scraper service.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokHealthCheckTest() throws ApiException {
        Object response = api.tiktokHealthCheck();
        // TODO: test validations
    }

    /**
     * Health check
     *
     * Check health of the TikTok scraper service.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokHealthCheckHeadTest() throws ApiException {
        Object response = api.tiktokHealthCheckHead();
        // TODO: test validations
    }

    /**
     * List regions
     *
     * List supported TikTok content regions.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokListRegionsTest() throws ApiException {
        Object response = api.tiktokListRegions();
        // TODO: test validations
    }

    /**
     * Search hashtags
     *
     * Search TikTok hashtags by keyword.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokSearchHashtagsTest() throws ApiException {
        String query = null;
        String region = null;
        Integer count = null;
        String cursor = null;
        Object response = api.tiktokSearchHashtags(query, region, count, cursor);
        // TODO: test validations
    }

    /**
     * Search the TikTok Ad Library
     *
     * Search TikTok&#39;s Commercial Content Library (ad transparency) by keyword or advertiser.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokSearchTheTiktokAdLibraryTest() throws ApiException {
        String query = null;
        String advertiserId = null;
        String region = null;
        Integer days = null;
        String sort = null;
        Integer offset = null;
        String searchId = null;
        Integer count = null;
        Object response = api.tiktokSearchTheTiktokAdLibrary(query, advertiserId, region, days, sort, offset, searchId, count);
        // TODO: test validations
    }

    /**
     * Search TikTok advertisers
     *
     * Look up TikTok advertiser business ids by name (feeds ads/search?advertiser_id&#x3D;).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokSearchTiktokAdvertisersTest() throws ApiException {
        String query = null;
        String region = null;
        Integer count = null;
        Object response = api.tiktokSearchTiktokAdvertisers(query, region, count);
        // TODO: test validations
    }

    /**
     * Search TikTok Shop products
     *
     * Keyword search over TikTok Shop products (US): products with their bound video, matching shops, related searches and categories.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokSearchTiktokShopProductsTest() throws ApiException {
        String q = null;
        Object response = api.tiktokSearchTiktokShopProducts(q);
        // TODO: test validations
    }

    /**
     * Search users
     *
     * Search TikTok users by keyword.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokSearchUsersTest() throws ApiException {
        String query = null;
        String region = null;
        Integer count = null;
        String cursor = null;
        Object response = api.tiktokSearchUsers(query, region, count, cursor);
        // TODO: test validations
    }

    /**
     * Search videos
     *
     * Search TikTok videos by keyword.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokSearchVideosTest() throws ApiException {
        String query = null;
        String region = null;
        Integer count = null;
        String cursor = null;
        Object response = api.tiktokSearchVideos(query, region, count, cursor);
        // TODO: test validations
    }

    /**
     * TikTok Shop best sellers
     *
     * TikTok Shop&#39;s own ranking of the best-selling products of the past 30 days (US).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokTiktokShopBestSellersTest() throws ApiException {
        Integer count = null;
        Object response = api.tiktokTiktokShopBestSellers(count);
        // TODO: test validations
    }

    /**
     * TikTok Shop category: subcategories + top products
     *
     * A category&#39;s subcategories and its top products as TikTok Shop ranks them (US).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokTiktokShopCategorySubcategoriesTopProductsTest() throws ApiException {
        String categoryId = null;
        Object response = api.tiktokTiktokShopCategorySubcategoriesTopProducts(categoryId);
        // TODO: test validations
    }

    /**
     * TikTok Shop product detail
     *
     * Full TikTok Shop product page (US): description, images, price, SKUs with stock, reviews, shop and TikTok&#39;s AI summary.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokTiktokShopProductDetailTest() throws ApiException {
        String productId = null;
        Object response = api.tiktokTiktokShopProductDetail(productId);
        // TODO: test validations
    }

    /**
     * TikTok Shop root categories
     *
     * Top-level TikTok Shop categories (US). Drill down with /shop/categories/{category_id}.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokTiktokShopRootCategoriesTest() throws ApiException {
        Object response = api.tiktokTiktokShopRootCategories();
        // TODO: test validations
    }

    /**
     * Trending hashtags
     *
     * Get trending hashtags (mobile Discover surface — view_count + creators).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokTrendingHashtagsTest() throws ApiException {
        String region = null;
        Integer period = null;
        Integer count = null;
        Object response = api.tiktokTrendingHashtags(region, period, count);
        // TODO: test validations
    }

    /**
     * Trending songs
     *
     * Get trending songs/sounds (mobile hot-music feed — ranked by usage).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokTrendingSongsTest() throws ApiException {
        String region = null;
        Integer period = null;
        Integer count = null;
        Object response = api.tiktokTrendingSongs(region, period, count);
        // TODO: test validations
    }

    /**
     * Trending videos
     *
     * Get trending videos from the TikTok Explore feed.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tiktokTrendingVideosTest() throws ApiException {
        String region = null;
        Integer count = null;
        Object response = api.tiktokTrendingVideos(region, count);
        // TODO: test validations
    }

}
