/*
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.scrapebadger.client.api;

import com.scrapebadger.client.ApiException;
import java.math.BigDecimal;
import com.scrapebadger.client.model.HTTPValidationError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VintedApi
 */
@Disabled
public class VintedApiTest {

    private final VintedApi api = new VintedApi();

    /**
     * Get item details
     *
     * Get detailed information about a Vinted item.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedGetItemDetailsTest() throws ApiException {
        Integer itemId = null;
        String market = null;
        Object response = api.vintedGetItemDetails(itemId, market);
        // TODO: test validations
    }

    /**
     * Get user profile
     *
     * Get a Vinted user&#39;s profile.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedGetUserProfileTest() throws ApiException {
        Integer userId = null;
        String market = null;
        Object response = api.vintedGetUserProfile(userId, market);
        // TODO: test validations
    }

    /**
     * Get user&#39;s listed items
     *
     * Get items listed by a Vinted user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedGetUserSListedItemsTest() throws ApiException {
        Integer userId = null;
        String market = null;
        Integer page = null;
        Integer perPage = null;
        Object response = api.vintedGetUserSListedItems(userId, market, page, perPage);
        // TODO: test validations
    }

    /**
     * List colors
     *
     * Get available Vinted colors for filtering.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedListColorsTest() throws ApiException {
        String market = null;
        Object response = api.vintedListColors(market);
        // TODO: test validations
    }

    /**
     * List item conditions
     *
     * Get available item condition statuses.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedListItemConditionsTest() throws ApiException {
        String market = null;
        Object response = api.vintedListItemConditions(market);
        // TODO: test validations
    }

    /**
     * List markets
     *
     * List all supported Vinted markets.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedListMarketsTest() throws ApiException {
        Object response = api.vintedListMarkets();
        // TODO: test validations
    }

    /**
     * Search brands
     *
     * Search Vinted brands.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedSearchBrandsTest() throws ApiException {
        String keyword = null;
        String market = null;
        Object response = api.vintedSearchBrands(keyword, market);
        // TODO: test validations
    }

    /**
     * Search Vinted items
     *
     * Search Vinted catalog items with filters.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedSearchVintedItemsTest() throws ApiException {
        String query = null;
        String market = null;
        String sellerCountry = null;
        Integer page = null;
        Integer perPage = null;
        BigDecimal priceFrom = null;
        BigDecimal priceTo = null;
        String brandIds = null;
        String catalogIds = null;
        String colorIds = null;
        String statusIds = null;
        String order = null;
        Object response = api.vintedSearchVintedItems(query, market, sellerCountry, page, perPage, priceFrom, priceTo, brandIds, catalogIds, colorIds, statusIds, order);
        // TODO: test validations
    }

    /**
     * Vinted scraper health check
     *
     * Check health of the Vinted scraper service.  Accepts &#x60;&#x60;HEAD&#x60;&#x60; so external uptime checkers (UptimeRobot uses HEAD by default for HTTP monitors) don&#39;t get a 405 Method Not Allowed.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedVintedScraperHealthCheckTest() throws ApiException {
        Object response = api.vintedVintedScraperHealthCheck();
        // TODO: test validations
    }

    /**
     * Vinted scraper health check
     *
     * Check health of the Vinted scraper service.  Accepts &#x60;&#x60;HEAD&#x60;&#x60; so external uptime checkers (UptimeRobot uses HEAD by default for HTTP monitors) don&#39;t get a 405 Method Not Allowed.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedVintedScraperHealthCheckHeadTest() throws ApiException {
        Object response = api.vintedVintedScraperHealthCheckHead();
        // TODO: test validations
    }

}
