/*
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.scrapebadger.client.api;

import com.scrapebadger.client.ApiException;
import java.math.BigDecimal;
import com.scrapebadger.client.model.BrandsResponse;
import com.scrapebadger.client.model.ColorsResponse;
import com.scrapebadger.client.model.HTTPValidationError;
import com.scrapebadger.client.model.ItemDetailResponse;
import com.scrapebadger.client.model.MarketsResponse;
import com.scrapebadger.client.model.SearchResponse;
import com.scrapebadger.client.model.StatusesResponse;
import com.scrapebadger.client.model.UserItemsResponse;
import com.scrapebadger.client.model.UserProfileResponse;
import com.scrapebadger.client.model.VintedImageSearchRequest;
import com.scrapebadger.client.model.VintedMobileReadRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VintedApi
 */
@Disabled
public class VintedApiTest {

    private final VintedApi api = new VintedApi();

    /**
     * Get item details
     *
     * Get detailed information about a Vinted item.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedGetItemDetailsTest() throws ApiException {
        Integer itemId = null;
        String market = null;
        ItemDetailResponse response = api.vintedGetItemDetails(itemId, market);
        // TODO: test validations
    }

    /**
     * Get user profile
     *
     * Get a Vinted user&#39;s profile.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedGetUserProfileTest() throws ApiException {
        Integer userId = null;
        String market = null;
        UserProfileResponse response = api.vintedGetUserProfile(userId, market);
        // TODO: test validations
    }

    /**
     * Get user&#39;s listed items
     *
     * Get items listed by a Vinted user.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedGetUserSListedItemsTest() throws ApiException {
        Integer userId = null;
        String market = null;
        Integer page = null;
        Integer perPage = null;
        UserItemsResponse response = api.vintedGetUserSListedItems(userId, market, page, perPage);
        // TODO: test validations
    }

    /**
     * List colors
     *
     * Get available Vinted colors for filtering.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedListColorsTest() throws ApiException {
        String market = null;
        ColorsResponse response = api.vintedListColors(market);
        // TODO: test validations
    }

    /**
     * List item conditions
     *
     * Get available item condition statuses.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedListItemConditionsTest() throws ApiException {
        String market = null;
        StatusesResponse response = api.vintedListItemConditions(market);
        // TODO: test validations
    }

    /**
     * List markets
     *
     * List all supported Vinted markets.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedListMarketsTest() throws ApiException {
        MarketsResponse response = api.vintedListMarkets();
        // TODO: test validations
    }

    /**
     * List public Vinted mobile operations
     *
     * Discover public read operations, parameters and runnable examples. Free.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedListPublicVintedMobileOperationsTest() throws ApiException {
        Object response = api.vintedListPublicVintedMobileOperations();
        // TODO: test validations
    }

    /**
     * Read Vinted mobile data
     *
     * Read catalog, listing, seller, review, sold-comparable, pricing, reference, shipping-reference, homepage or help data. No Vinted account is required. This is an allowlisted read API, including read-only upstream POST queries. Returns operation, market, and the upstream JSON under data. One credit. Sold comparable prices are not guaranteed final negotiated sale prices.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedReadVintedMobileDataTest() throws ApiException {
        String operation = null;
        VintedMobileReadRequest vintedMobileReadRequest = null;
        Object response = api.vintedReadVintedMobileData(operation, vintedMobileReadRequest);
        // TODO: test validations
    }

    /**
     * Search brands
     *
     * Search Vinted brands.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedSearchBrandsTest() throws ApiException {
        String keyword = null;
        String market = null;
        BrandsResponse response = api.vintedSearchBrands(keyword, market);
        // TODO: test validations
    }

    /**
     * Search by image
     *
     * Find active Vinted listings from a photo. 10 credits per successful request. Returns the usual items, pagination and market envelope. Visual ranking. Each item carries &#x60;similarity_score&#x60; on the calls where Vinted returns a ranking, and null on the ones where it does not -- a null says nothing about the item. The score sits on an unbounded scale that Vinted changes without notice (0-1 in Sep 2026, ~36-44 since): compare it only with the other items in the SAME response, never to a fixed cut-off. Resend the same image and pagination time for subsequent pages. Structured brand data may be null.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedSearchByImageTest() throws ApiException {
        VintedImageSearchRequest vintedImageSearchRequest = null;
        SearchResponse response = api.vintedSearchByImage(vintedImageSearchRequest);
        // TODO: test validations
    }

    /**
     * Search Vinted items
     *
     * Search Vinted catalog items with filters.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedSearchVintedItemsTest() throws ApiException {
        String query = null;
        String market = null;
        String sellerCountry = null;
        Integer page = null;
        Integer perPage = null;
        BigDecimal priceFrom = null;
        BigDecimal priceTo = null;
        String brandIds = null;
        String catalogIds = null;
        String colorIds = null;
        String sizeIds = null;
        String materialIds = null;
        Integer time = null;
        String searchSessionId = null;
        String statusIds = null;
        String order = null;
        SearchResponse response = api.vintedSearchVintedItems(query, market, sellerCountry, page, perPage, priceFrom, priceTo, brandIds, catalogIds, colorIds, sizeIds, materialIds, time, searchSessionId, statusIds, order);
        // TODO: test validations
    }

    /**
     * Vinted scraper health check
     *
     * Check health of the Vinted scraper service.  Accepts &#x60;&#x60;HEAD&#x60;&#x60; so external uptime checkers (UptimeRobot uses HEAD by default for HTTP monitors) don&#39;t get a 405 Method Not Allowed.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedVintedScraperHealthCheckTest() throws ApiException {
        Object response = api.vintedVintedScraperHealthCheck();
        // TODO: test validations
    }

    /**
     * Vinted scraper health check
     *
     * Check health of the Vinted scraper service.  Accepts &#x60;&#x60;HEAD&#x60;&#x60; so external uptime checkers (UptimeRobot uses HEAD by default for HTTP monitors) don&#39;t get a 405 Method Not Allowed.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void vintedVintedScraperHealthCheckHeadTest() throws ApiException {
        Object response = api.vintedVintedScraperHealthCheckHead();
        // TODO: test validations
    }

}
