/*
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.scrapebadger.client.api;

import com.scrapebadger.client.ApiException;
import com.scrapebadger.client.model.HTTPValidationError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WebApi
 */
@Disabled
public class WebApiTest {

    private final WebApi api = new WebApi();

    /**
     * Detect anti-bot and CAPTCHA systems
     *
     * Detect which anti-bot and CAPTCHA systems are present on a URL.  Uses rnet to fetch the page and identify DataDome, Cloudflare, Akamai, Kasada, Amazon WAF, reCAPTCHA, hCaptcha, GeeTest, and more. Cost: 1 credit.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void webDetectAntiBotAndCaptchaSystemsTest() throws ApiException {
        Object response = api.webDetectAntiBotAndCaptchaSystems();
        // TODO: test validations
    }

    /**
     * Extract structured data
     *
     * Extract structured data from a URL using CSS or XPath selectors. (Phase 6)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void webExtractStructuredDataTest() throws ApiException {
        Object response = api.webExtractStructuredData();
        // TODO: test validations
    }

    /**
     * Get batch job status
     *
     * Get the status of a batch scraping job. (Phase 6)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void webGetBatchJobStatusTest() throws ApiException {
        String jobId = null;
        Object response = api.webGetBatchJobStatus(jobId);
        // TODO: test validations
    }

    /**
     * Poll an auto-unblock discovery job
     *
     * Return the status + progress narration for an auto-unblock job.  Polled by the playground loader. &#x60;&#x60;job_id&#x60;&#x60; is an unguessable UUID handed out in the &#x60;&#x60;202 unblocking&#x60;&#x60; envelope and acts as a capability token, so any authenticated caller holding it can read the job (this is what lets several users share one discovery run&#39;s loader).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void webPollAnAutoUnblockDiscoveryJobTest() throws ApiException {
        String jobId = null;
        Object response = api.webPollAnAutoUnblockDiscoveryJob(jobId);
        // TODO: test validations
    }

    /**
     * Scrape a URL
     *
     * Scrape a URL and return its content.  The Generic Web Scraping API is fully user-driven: callers pick their own request parameters (engine, proxy tier, country, JS rendering, …). A blocked target surfaces the raw 422 &#x60;&#x60;blocking_page_detected&#x60;&#x60; so the caller can tune parameters themselves — we do NOT auto-trigger host discovery. Curated per-origin overrides (which the dedicated scraper APIs depend on) still apply.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void webScrapeAUrlTest() throws ApiException {
        Object response = api.webScrapeAUrl();
        // TODO: test validations
    }

    /**
     * Submit batch scraping job
     *
     * Submit a batch of URLs for scraping. (Phase 6)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void webSubmitBatchScrapingJobTest() throws ApiException {
        Object response = api.webSubmitBatchScrapingJob();
        // TODO: test validations
    }

    /**
     * Take a screenshot
     *
     * Take a screenshot of a URL. (browser engine)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void webTakeAScreenshotTest() throws ApiException {
        Object response = api.webTakeAScreenshot();
        // TODO: test validations
    }

    /**
     * Web scraper health check
     *
     * Check health of the web scraper service.  Bypasses the proxy abstraction because web-scraper exposes &#x60;&#x60;/health&#x60;&#x60; at the root (no &#x60;&#x60;/api/v1&#x60;&#x60; prefix, unlike the other scraper services).  Accepts &#x60;&#x60;HEAD&#x60;&#x60; so external uptime checkers (UptimeRobot uses HEAD by default for HTTP monitors) don&#39;t get a 405 Method Not Allowed.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void webWebScraperHealthCheckTest() throws ApiException {
        Object response = api.webWebScraperHealthCheck();
        // TODO: test validations
    }

    /**
     * Web scraper health check
     *
     * Check health of the web scraper service.  Bypasses the proxy abstraction because web-scraper exposes &#x60;&#x60;/health&#x60;&#x60; at the root (no &#x60;&#x60;/api/v1&#x60;&#x60; prefix, unlike the other scraper services).  Accepts &#x60;&#x60;HEAD&#x60;&#x60; so external uptime checkers (UptimeRobot uses HEAD by default for HTTP monitors) don&#39;t get a 405 Method Not Allowed.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void webWebScraperHealthCheckHeadTest() throws ApiException {
        Object response = api.webWebScraperHealthCheckHead();
        // TODO: test validations
    }

}
